const assert=require('node:assert/strict'),vm=require('node:vm');
let input='';process.stdin.on('data',chunk=>input+=chunk);process.stdin.on('end',async()=>{
 const {code,fixture}=JSON.parse(input),nodes=new Map(),listeners={},timers=new Map(),frames=new Map(),requests=[],draws=[];let seq=0,payload=structuredClone(fixture),failure=false,oversized=false,now=Date.parse(fixture.generated_at),workspaceChanged=null,mediaChanged=null,resized=null,transforms=[];
 const ctx=()=>({globalAlpha:1,fillStyle:'',strokeStyle:'',setTransform(...values){transforms.push(values);},clearRect(){},createRadialGradient(){return {addColorStop(){}};},beginPath(){},rect(){},arc(x,y,r){draws.push({x,y,r,color:this.fillStyle});},moveTo(){},lineTo(){},fill(){},stroke(){}});
 function element(tag=''){return {tag,hidden:false,open:false,disabled:false,width:640,height:560,textContent:'',children:[],dataset:{},attributes:{},events:{},value:'',setAttribute(k,v){this.attributes[k]=v;},append(...v){this.children.push(...v);},replaceChildren(...v){this.children=v;},addEventListener(k,v){this.events[k]=v;},getContext:()=>ctx(),focus(){},setPointerCapture(){}};}
 const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};const document={hidden:false,getElementById:get,createElement:element,addEventListener:(k,v)=>listeners[k]=v};
 const media={matches:false,addEventListener:(_k,v)=>mediaChanged=v};const window={devicePixelRatio:3,matchMedia:()=>media,setTimeout(fn,ms){const id=++seq;timers.set(id,{fn,ms});return id;},clearTimeout(id){timers.delete(id);},requestAnimationFrame(fn){const id=++seq;frames.set(id,fn);return id;},cancelAnimationFrame(id){frames.delete(id);},megalodonSupportConfiguration:{refresh:()=>{},open:()=>{get('configured').textContent='open';}}};
 class Clock extends Date{static now(){return now;}}
 const context={localHudLaunch:{},document,window,Date:Clock,TextEncoder,TextDecoder,Uint8Array,AbortController,ResizeObserver:class{constructor(fn){resized=fn;}observe(){}},MutationObserver:class{constructor(fn){workspaceChanged=fn;}observe(){}},fetch:async(path,options)=>{requests.push({path,options});if(failure)throw Error('offline');return {ok:true,headers:{get:()=>oversized?'262145':null},text:async()=>JSON.stringify(payload)};}};
 const settle=()=>new Promise(resolve=>setImmediate(resolve));const click=id=>get(id).events.click();const particles=()=>draws.filter(d=>d.r===2.3);const poll=async()=>{const entry=[...timers].find(([,v])=>v.ms===2000);assert.ok(entry,'2s poll scheduled');timers.delete(entry[0]);await entry[1].fn();await settle();};const frame=time=>{const entry=[...frames][0];assert.ok(entry,'animation scheduled');frames.delete(entry[0]);draws.length=0;entry[1](time);};
 get('operations-history').open=true;vm.runInNewContext(code,context);await settle();const math=vm.runInNewContext('LiveGlobeMath',context);
 assert.equal(requests.length,1);assert.equal(requests[0].path,'/api/live-connections');assert.equal(requests[0].options.method,'GET');assert.equal(requests[0].options.headers['X-Megalodon-Check'],'1');assert.ok(requests.every(r=>r.options.method==='GET'));
 assert.match(get('live-coverage').textContent,/observed in this capture session/);assert.doesNotMatch(get('live-coverage').textContent,/bytes in retained flows/);assert.match(get('live-coverage').textContent,/Cache evictions: 0/);assert.equal(get('live-land').width,960,'DPR capped at 1.5');assert.equal(get('live-mapped-count').textContent,'1');assert.match(get('live-precision').textContent,/accuracy radius unknown/);assert.match(get('live-anchor').textContent,/Kansas/);assert.match(get('live-connection-rows').children[0].children[0].children[0].textContent,/precision unknown/);
 // One-way observations animate only one direction; a poll must not restart particle phase.
 frame(0);assert.equal(particles().length,1);assert.ok(draws.some(d=>d.r===236),'land and traffic render in the same animation frame');frame(16);assert.ok(draws.some(d=>d.r===236),'land is not throttled to a separate 15fps clock');frame(800);assert.equal(particles().length,1);const before={...particles()[0]};draws.length=0;await poll();const after=particles()[0];assert.ok(Math.abs(before.x-after.x)<1e-8&&Math.abs(before.y-after.y)<1e-8,'phase and orientation survive refresh');
 payload=structuredClone(fixture);payload.connections[0].b_to_a={packets:2,bytes:100,last_seen:fixture.generated_at};await poll();frame(832);assert.equal(particles().length,2,'only observed reverse traffic adds a second particle');assert.deepEqual(new Set(particles().map(p=>p.color)),new Set(['#72e7e2','#c7b0fc']));
 // Color derives from the local endpoint, never lexicographic A/B ordering.
 assert.equal(math.color({a:{local:false},b:{local:true}},'a_to_b'),'#c7b0fc');assert.equal(math.color({a:{local:false},b:{local:true}},'b_to_a'),'#72e7e2');assert.equal(math.color({a:{local:false},b:{local:false}},'a_to_b'),'#a8bed3');
 // Closed/stopped/old snapshots remain reference geometry with no traffic animation.
 payload.capture.state='stopped';await poll();frame(864);assert.equal(particles().length,0);payload=structuredClone(fixture);payload.connections[0].state='closed';await poll();frame(896);assert.equal(particles().length,0);
 payload=structuredClone(fixture);now+=9000;await poll();frame(928);assert.equal(particles().length,0);assert.match(get('live-globe-status').textContent,/Stale/);now=Date.parse(fixture.generated_at);
 payload=structuredClone(fixture);payload.connections[0].a_to_b.last_seen='2026-09-30T20:09:40Z';await poll();frame(960);assert.equal(particles().length,0,'old per-direction packet evidence cannot animate');
 payload=structuredClone(fixture);await poll();media.matches=true;mediaChanged();assert.equal(frames.size,0);draws.length=0;await poll();assert.equal(particles().length,0);assert.match(get('live-motion-status').textContent,/Reduced motion/);media.matches=false;mediaChanged();assert.equal(frames.size,1);
 click('live-globe-pause');assert.equal(frames.size,0);assert.equal(get('live-globe-pause').attributes['aria-pressed'],'true');click('live-globe-pause');assert.equal(frames.size,1);
 document.hidden=true;listeners.visibilitychange();assert.equal(frames.size,0);assert.equal([...timers.values()].filter(v=>v.ms===2000).length,0);document.hidden=false;listeners.visibilitychange();await settle();assert.equal(frames.size,1);
 get('workspace-live').hidden=true;workspaceChanged();assert.equal(frames.size,0);assert.equal([...timers.values()].filter(v=>v.ms===2000).length,0);get('workspace-live').hidden=false;workspaceChanged();await settle();
 payload=structuredClone(fixture);payload.geography.anchor=null;payload.geography.status='missing';payload.connections[0].b.location=null;payload.totals.unmapped=1;await poll();frame(992);assert.equal(particles().length,0);assert.equal(get('live-mapped-count').textContent,'0');assert.equal(get('live-unmapped-count').textContent,'1');assert.match(get('live-anchor').textContent,/unavailable/);
 payload=structuredClone(fixture);payload.connections=[];payload.totals={active:0,returned:0,unmapped:0,truncated:false,packets:0,bytes:0};payload.capture.accepted=0;await poll();assert.match(get('live-globe-status').textContent,/awaiting packets/);payload.capture.accepted=5;payload.totals.packets=5;payload.totals.bytes=500;await poll();assert.match(get('live-globe-status').textContent,/no recent connections/);frame(1024);assert.equal(particles().length,0);assert.match(get('live-connection-rows').children[0].children[0].textContent,/No recent connections/);
 failure=true;await poll();frame(1056);assert.equal(particles().length,0);assert.match(get('live-globe-status').textContent,/unavailable/);failure=false;oversized=true;await poll();assert.match(get('live-globe-status').textContent,/unavailable/);oversized=false;
 payload=structuredClone(fixture);payload.totals.evicted=12;payload.totals.truncated=true;await poll();assert.match(get('live-coverage').textContent,/Cache evictions: 12/);assert.match(get('live-coverage').textContent,/Partial coverage/);
 payload.totals.evicted=-1;await poll();assert.match(get('live-globe-status').textContent,/unavailable/);
 payload=structuredClone(fixture);payload.connections[0].a.location.latitude=100;await poll();assert.match(get('live-globe-status').textContent,/unavailable/);
 payload=structuredClone(fixture);payload.connections=Array.from({length:129},()=>fixture.connections[0]);await poll();assert.match(get('live-globe-status').textContent,/unavailable/);
 // Correct shortest spherical path across the anti-meridian, stable antipodes and coincidence.
 const route=math.route({latitude:0,longitude:179},{latitude:0,longitude:-179},1);assert.ok(route[24][0]<-1,'midpoint crosses Pacific dateline, not Greenwich');assert.ok(route.every(v=>v.every(Number.isFinite)));
 const anti=math.route({latitude:0,longitude:0},{latitude:0,longitude:180},1);assert.ok(anti.every(v=>v.every(Number.isFinite)));assert.ok(Math.abs(anti[48][0]+1)<1e-8);assert.equal(math.route({latitude:30,longitude:40},{latitude:30,longitude:40},1).length,1);
 const front=math.basis(0,0);assert.ok(math.project(math.vector(0,180),front).depth<0);assert.ok(math.project(math.vector(0,0),front).depth>0);const lane2=math.route({latitude:0,longitude:179},{latitude:0,longitude:-179},-1);assert.ok(Math.abs(route[24][2]-lane2[24][2])>.01,'bidirectional lanes stay separated');
 // Whole arcs on the back hemisphere are clipped, including moving dots.
 payload=structuredClone(fixture);payload.geography.anchor={...fixture.geography.anchor,latitude:0,longitude:0};payload.connections[0].a.location={...payload.geography.anchor,longitude:170};payload.connections[0].b.location={...payload.geography.anchor,longitude:175};await poll();click('live-globe-center');frame(1088);assert.equal(particles().length,0);
 payload=structuredClone(fixture);payload.recording_mode='connection_summaries';await poll();assert.match(get('live-coverage').textContent,/sensor-reported packets/);assert.match(get('live-coverage').textContent,/connection-summary updates/);assert.match(get('live-globe-status').textContent,/Sensor-reported exchange/);get('live-globe-stage').getBoundingClientRect=()=>({width:960,height:700});resized();assert.equal(get('live-land').width,1440,'backing pixels follow the visible surface');assert.equal(get('live-flows').height,1050);const transform=transforms.at(-1);assert.equal(transform[0],transform[3],'equal axis scale keeps the globe spherical');assert.ok(transform[4]>0,'wide surfaces are letterboxed instead of stretched');click('live-interface-change');assert.equal(get('configured').textContent,'open');
 console.log('live globe geometry, direction, freshness and visibility checks passed');
}).on('error',error=>{console.error(error);process.exitCode=1;});process.on('unhandledRejection',error=>{console.error(error);process.exitCode=1;});
