const assert=require('node:assert/strict'),vm=require('node:vm');let input='';process.stdin.on('data',x=>input+=x);process.stdin.on('end',async()=>{
 const {code,fixture}=JSON.parse(input),nodes=new Map(),listeners={},timers=new Map(),requests=[];let serial=0,payload=structuredClone(fixture),failure=false,selected=null,held=null,now=Date.parse(fixture.observed_at);
 function element(tag=''){const classes=new Set();const n={tag,textContent:'',children:[],attrs:{},dataset:{},events:{},hidden:false,disabled:false,value:'',checked:false,open:false,style:{},className:'',classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle(x,v){v?classes.add(x):classes.delete(x);}},setAttribute(k,v){this.attrs[k]=String(v);},append(...v){this.children.push(...v);},replaceChildren(...v){this.children=v;this.textContent='';},addEventListener(k,f){this.events[k]=f;},focus(){document.activeElement=this;}};Object.defineProperty(n,'firstChild',{get(){return this.children[0];}});Object.defineProperty(n,'innerHTML',{set(){throw Error('unsafe HTML sink');}});return n;}
 const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};get('workspace-setup').hidden=true;
 const document={hidden:false,activeElement:null,getElementById:get,createElement:element,createElementNS:(_,tag)=>element(tag),addEventListener:(name,fn)=>listeners[name]=fn};
 const window={addEventListener:(name,fn)=>listeners[name]=fn,MegalodonOperations:{selectEndpoint(ip,metadata){selected={ip,metadata};}}};
 class Clock extends Date{static now(){return now;}}
 const context={localHudLaunch:{},document,window,state:{paused:false},Date:Clock,TextDecoder,TextEncoder,Uint8Array,AbortController,AbortSignal,setTimeout(fn,ms){const id=++serial;timers.set(id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id),fetch:async(path,opts)=>{requests.push({path,opts});if(held)await held;if(failure)throw Error('private detail');const data=path.startsWith('/api/network/history')?{schema:'megalodon-device-history-v1',records:[{observed_at:fixture.observed_at,node:fixture.nodes[2]}],gaps:[],next_cursor:null}:payload;const bytes=new TextEncoder().encode(JSON.stringify(data));let done=false;return {ok:true,body:{getReader:()=>({read:async()=>done?{done:true}:(done=true,{done:false,value:bytes}),cancel:async()=>{}})}};}};
 const settle=()=>new Promise(r=>setImmediate(r)),all=n=>[n,...n.children.flatMap(all)],text=n=>n.textContent+n.children.map(text).join(' '),click=async id=>{get(id).events.click();await settle();await settle();},poll=async()=>{const timer=[...timers].find(([,v])=>v.ms===5000);assert.ok(timer);timers.delete(timer[0]);await timer[1].fn();await settle();await settle();},flushTimer=async ms=>{const timer=[...timers].find(([,v])=>v.ms===ms);assert.ok(timer);timers.delete(timer[0]);await timer[1].fn();await settle();await settle();};
 const directory=()=>all(get('network-directory')).filter(n=>n.dataset.networkSurface==='directory'),byId=id=>directory().find(n=>n.dataset.networkNode===id);
 vm.runInNewContext(code,context);await settle();await settle();assert.equal(requests.length,1);assert.equal(requests[0].opts.headers['X-Megalodon-Check'],'1');assert.equal(get('network-save').disabled,false);assert.equal(get('network-enabled').checked,false);assert.equal(requests.filter(r=>r.opts.method==='POST').length,0);
 assert.equal(directory().length,2,'this computer does not repeat in the device directory');assert.equal(get('network-computer-list').children.length,1);assert.equal(get('network-selection-content').hidden,true);assert.match(text(get('network-directory')),/Traffic seen/);assert.match(text(get('network-directory')),/Found, traffic not visible/);assert.equal(all(get('network-directory')).filter(n=>n.tag==='svg'||n.tag==='path').length,0,'overview is a directory, not a tangled diagram');
 // Selecting a discovery-only address stays inline, requests nothing, and does not invent traffic.
 const beforeSelection=requests.length;byId('discovered').events.click();assert.equal(selected,null,'ordinary selection never opens the distant inspector');assert.equal(requests.length,beforeSelection);assert.equal(get('network-selected-title').textContent,'Unnamed device');assert.equal(get('network-selected-address').textContent,'192.168.2.30');assert.equal(get('network-selected-traffic').hidden,true);assert.match(get('network-selected-summary').textContent,/cannot see its traffic/);assert.match(get('network-selected-summary').textContent,/does not mean it is offline/);assert.equal(get('network-counterpart-list').children.length,0,'discovery paths are not observed exchanges');
 // On a phone, selecting an item aligns the detail heading at the top, even
 // when the entire detail panel is taller than the viewport. Focus stays on
 // the keyboard-operated directory control rather than jumping elsewhere.
 let detailScroll=null;get('network-selection').scrollIntoView=options=>{detailScroll=options;};window.matchMedia=()=>({matches:true});const mobileChoice=byId('discovered');mobileChoice.focus();mobileChoice.events.click();assert.equal(detailScroll.block,'start');assert.equal(detailScroll.behavior,'auto');assert.equal(document.activeElement,mobileChoice);delete window.matchMedia;
 await click('network-open-inspector');assert.equal(selected.ip,'192.168.2.30');assert.equal(selected.metadata.discovery_only,true);selected=null;await click('network-open-history');assert.ok(requests.at(-1).path.startsWith('/api/network/history?'));assert.equal(get('network-history-rows').children.length,1);assert.match(get('network-history-status').textContent,/Storage & history/);
 // Per-address byte directions and source-qualified service names remain distinct.
 payload=structuredClone(fixture);payload.nodes[1].names=[{name:'service.example',source:'Observed TLS SNI',observed_at:fixture.observed_at}];payload.nodes[1].services=[{name:'tls',role:'observed endpoint'}];await poll();byId('peer').events.click();assert.equal(selected,null);assert.equal(get('network-selected-title').textContent,'Unnamed device','a service hostname is not promoted to a device identity');assert.equal(get('network-selected-traffic').hidden,false);assert.equal(get('network-selected-sent').textContent,'100 B');assert.equal(get('network-selected-received').textContent,'200 B');assert.equal(get('network-sent-bar').style.width,'50%');assert.equal(get('network-received-bar').style.width,'100%');assert.match(text(get('network-selected-names')),/service.example · Observed TLS SNI/);assert.match(get('network-selected-services').textContent,/Encrypted connections \(TLS\)/);assert.match(text(get('network-selected-service-details')),/tls · observed endpoint/);assert.equal(get('network-counterpart-list').children.length,1);assert.match(text(get('network-counterpart-list')),/This computer/);
 const focusDirectory=byId('peer');focusDirectory.focus();await poll();assert.equal(document.activeElement,focusDirectory,'unchanged directory controls retain DOM and focus');assert.equal(byId('peer').attrs['aria-pressed'],'true');assert.equal(get('network-selected-address').textContent,'192.168.2.20');const tableFocus=get('network-rows').children[2].children[0].children[0];tableFocus.focus();await poll();assert.equal(document.activeElement.dataset.networkNode,'discovered');assert.notEqual(document.activeElement,tableFocus,'technical-table focus is restored after refresh');
 const suggestion=get('network-available').children[0],options=get('network-group').children;suggestion.focus();await poll();assert.equal(document.activeElement,suggestion);assert.equal(get('network-group').children,options);
 get('network-scopes').value='192.168.2.0/24';get('network-scopes').events.input();await poll();assert.equal(get('network-scopes').value,'192.168.2.0/24');get('network-enabled').checked=true;payload={...fixture,settings:{...fixture.settings,enabled:true,scopes:['192.168.2.0/24']},discovery:{...fixture.discovery,state:'waiting'}};
 await get('network-setup-form').events.submit({preventDefault(){}});await settle();const post=requests.find(r=>r.opts.method==='POST');assert.equal(post.opts.headers['X-Megalodon-Network-Token'],fixture.token);assert.deepEqual(JSON.parse(post.opts.body),{action:'configure',scopes:['192.168.2.0/24'],enabled:true});assert.match(get('network-setup-status').textContent,/Discovery enabled/);
 failure=true;await poll();assert.equal(get('network-panel').classList.contains('snapshot-stale'),true);assert.match(get('network-observed').textContent,/Previous observations/);assert.equal(get('network-selected-state').textContent,'PREVIOUS OBSERVATIONS');assert.equal(get('network-counterpart-list').children.length,0,'stale relationships cannot appear current');failure=false;
 context.state.paused=true;await window.MegalodonNetwork.refresh();const pausedReads=requests.length;assert.equal([...timers.values()].filter(x=>x.ms===5000).length,0);assert.equal(requests.length,pausedReads);context.state.paused=false;document.hidden=true;listeners.visibilitychange();const hiddenReads=requests.length;await window.MegalodonNetwork.refresh();assert.equal([...timers.values()].filter(x=>x.ms===5000).length,0);assert.equal(requests.length,hiddenReads);document.hidden=false;listeners.visibilitychange();await settle();await settle();
 payload={...fixture,edges:[{...fixture.edges[0],target:'missing'}]};await poll();assert.equal(get('network-panel').classList.contains('snapshot-stale'),true,'invalid source relationships reject the response');payload={...fixture,nodes:[],edges:[],total:0};await poll();assert.match(text(get('network-directory')),/No other device addresses/);assert.match(get('network-selected-freshness').textContent,/outside the current page/);assert.equal(get('network-next').disabled,true);
 // Large pages preserve every address without duplicating PC identities or hiding technical rows.
 const large=structuredClone(fixture);large.groups=[{id:'eth0',label:'eth0',kind:'lan'},{id:'tun0',label:'Private VPN',kind:'vpn'},{id:'docker0',label:'Containers',kind:'container'}];large.total=180;large.limit=50;large.nodes=Array.from({length:50},(_,i)=>({...fixture.nodes[i<17?0:2],id:'n'+i,ip:i===49?'2001:db8:1234:5678:1234:5678:1234:5678':`192.168.2.${i+1}`,group:i>=45?'tun0':i<10?'docker0':'eth0',role:i<17?'pc':i===17?'gateway':'device',observed:i===18||i===19}));large.edges=large.nodes.slice(18).map((n,i)=>({...fixture.edges[0],id:'e'+i,source:'n0',target:n.id}));payload=large;await poll();assert.equal(get('network-computer-list').children.length,17);assert.match(get('network-computer-note').textContent,/not separate devices/);assert.equal(get('network-router-list').children.length,1);assert.equal(directory().length,32);assert.equal(get('network-rows').children.length,50);assert.equal(get('network-page').textContent,'1–50 of 180 addresses');assert.match(get('network-directory-status').textContent,/50 returned addresses/);assert.equal(byId('n49').children[1].textContent,large.nodes[49].ip,'complete IPv6 remains readable and accessible');
 const secondary=all(get('network-directory')).find(n=>n.tag==='details');assert.equal(secondary.open,false,'VPN peers are secondary, collapsed context');secondary.open=true;secondary.events.toggle();const summary=secondary.children[0];summary.focus();await poll();assert.equal(document.activeElement,summary,'refresh does not rebuild a focused disclosure');assert.equal(all(get('network-directory')).find(n=>n.tag==='details'),secondary);
 get('network-computer-list').children[0].children[0].events.click();assert.equal(get('network-selected-title').textContent,'This computer');assert.equal(get('network-counterpart-list').children.length,10,'one-device exchanges are paged, never a giant diagram');assert.equal(get('network-counterpart-page').textContent,'1–10 of 32');await click('network-counterpart-next');assert.equal(get('network-counterpart-page').textContent,'11–20 of 32');
 payload={...large,offset:50};await click('network-next');assert.match(requests.at(-1).path,/offset=50&limit=50/);assert.equal(get('network-page').textContent,'51–100 of 180 addresses');payload={...large,offset:0,limit:100,nodes:[...large.nodes,...large.nodes.map((n,i)=>({...n,id:'extra'+i,ip:`192.168.3.${i+1}`}))]};get('network-page-size').value='100';get('network-page-size').events.change();await flushTimer(0);assert.match(requests.at(-1).path,/offset=0&limit=100/);assert.equal(get('network-rows').children.length,100);assert.equal(directory().length,64);
 payload={...fixture,nodes:[{...fixture.nodes[2],name:'Observed device name'}],edges:[],total:1};get('network-search').value='printer';get('network-search').events.input();await flushTimer(250);await flushTimer(0);assert.match(requests.at(-1).path,/query=printer/);assert.equal(directory().length,1);assert.equal(directory()[0].children[0].textContent,'Observed device name');assert.equal(get('network-rows').children.length,1);assert.equal(get('network-computer-addresses').hidden,true,'off-page computer addresses are not fabricated');
 payload={...fixture,nodes:[{...fixture.nodes[2],name:'<img src=x onerror=bad()>',names:[{name:'<script>unsafe</script>',source:'Observed TLS SNI'}]}],edges:[],total:1};await poll();directory()[0].events.click();assert.equal(get('network-selected-title').textContent,payload.nodes[0].name);assert.match(text(get('network-selected-names')),/<script>unsafe<\/script>/);assert.equal(all(get('network-directory')).some(n=>['img','script','svg','path'].includes(n.tag)),false,'untrusted text never becomes markup');
 payload=fixture;let release;held=new Promise(r=>release=r);window.MegalodonNetwork.refresh();await settle();const inflight=requests.length;window.MegalodonNetwork.refresh();assert.equal(requests.length,inflight);release();held=null;await settle();
 console.log('network directory, inline activity, bounded paging, source truth and protected setup passed');
}).on('error',error=>{console.error(error);process.exitCode=1;});process.on('unhandledRejection',error=>{console.error(error);process.exitCode=1;});
