const assert=require('node:assert/strict'),vm=require('node:vm');let input='';process.stdin.on('data',x=>input+=x);process.stdin.on('end',async()=>{
 const {code,fixture}=JSON.parse(input),nodes=new Map(),listeners={},timers=new Map(),requests=[];let serial=0,payload=fixture,failure=false,selected=null,held=null,now=Date.parse(fixture.observed_at);
 function element(tag=''){const classes=new Set();const n={tag,textContent:'',children:[],attrs:{},dataset:{},events:{},hidden:false,disabled:false,value:'',checked:false,className:'',classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle(x,v){v?classes.add(x):classes.delete(x);}},setAttribute(k,v){this.attrs[k]=String(v);},append(...v){this.children.push(...v);},replaceChildren(...v){this.children=v;this.textContent='';},addEventListener(k,f){this.events[k]=f;},focus(){document.activeElement=this;}};Object.defineProperty(n,'firstChild',{get(){return this.children[0];}});Object.defineProperty(n,'innerHTML',{set(){throw Error('unsafe HTML sink');}});return n;}
 const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};get('workspace-setup').hidden=true;
 const document={hidden:false,activeElement:null,getElementById:get,createElement:element,createElementNS:(_,tag)=>element(tag),addEventListener:(name,fn)=>listeners[name]=fn};
 const window={addEventListener:(name,fn)=>listeners[name]=fn,MegalodonOperations:{selectEndpoint(ip,metadata){selected={ip,metadata};}}};
 class Clock extends Date{static now(){return now;}}
 const context={localHudLaunch:{},document,window,state:{paused:false},Date:Clock,TextDecoder,TextEncoder,Uint8Array,AbortController,AbortSignal,setTimeout(fn,ms){const id=++serial;timers.set(id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id),fetch:async(path,opts)=>{requests.push({path,opts});if(held)await held;if(failure)throw Error('private detail');const bytes=new TextEncoder().encode(JSON.stringify(payload));let done=false;return {ok:true,body:{getReader:()=>({read:async()=>done?{done:true}:(done=true,{done:false,value:bytes}),cancel:async()=>{}})}};}};
 const settle=()=>new Promise(r=>setImmediate(r)),all=n=>[n,...n.children.flatMap(all)],click=async id=>{get(id).events.click();await settle();await settle();},poll=async()=>{const timer=[...timers].find(([,v])=>v.ms===5000);assert.ok(timer);timers.delete(timer[0]);await timer[1].fn();await settle();await settle();};
 vm.runInNewContext(code,context);await settle();await settle();assert.equal(requests.length,1);assert.equal(requests[0].opts.headers['X-Megalodon-Check'],'1');assert.equal(get('network-map').children[0].tag,'svg');assert.equal(get('network-save').disabled,false);assert.equal(get('network-enabled').checked,false);assert.equal(requests.filter(r=>r.opts.method==='POST').length,0);
 const picture=get('network-map').children[0],paths=all(picture).filter(n=>n.tag==='path');assert.equal(paths.filter(n=>n.attrs.class==='net-flow outbound').length,1);assert.equal(paths.filter(n=>n.attrs.class==='net-flow inbound').length,1);assert.equal(paths.filter(n=>n.attrs.class==='net-edge discovered').length,1);
 const focusMap=all(picture).find(n=>n.dataset.networkNode==='peer');focusMap.focus();await poll();assert.equal(document.activeElement.dataset.networkNode,'peer');assert.notEqual(document.activeElement,focusMap,'map focus restored onto current DOM node');const rowFocus=get('network-rows').children[2].children[0].children[0];rowFocus.focus();await poll();assert.equal(document.activeElement.dataset.networkNode,'discovered');assert.equal(document.activeElement.dataset.networkSurface,'list');assert.notEqual(document.activeElement,rowFocus,'table focus restored after refresh');
 const suggestion=get('network-available').children[0],options=get('network-group').children;suggestion.focus();await poll();assert.equal(document.activeElement,suggestion,'scope suggestion retains focus on unchanged inventory');assert.equal(get('network-available').children[0],suggestion);assert.equal(get('network-group').children,options,'unchanged select options are retained');
 const discovered=all(picture).find(n=>n.attrs['aria-label']?.startsWith('192.168.2.30'));discovered.events.click();assert.equal(selected.ip,'192.168.2.30');assert.equal(selected.metadata.discovery_only,true);assert.equal(requests.filter(r=>r.opts.method==='POST').length,0,'selection is read only');assert.equal(get('network-rows').children.length,3);
 get('network-scopes').value='192.168.2.0/24';get('network-scopes').events.input();await poll();assert.equal(get('network-scopes').value,'192.168.2.0/24','refresh preserves unsaved scopes');get('network-enabled').checked=true;
 payload={...fixture,settings:{...fixture.settings,enabled:true,scopes:['192.168.2.0/24']},discovery:{...fixture.discovery,state:'waiting'}};
 await get('network-setup-form').events.submit({preventDefault(){}});await settle();const post=requests.find(r=>r.opts.method==='POST');assert.ok(post);assert.equal(post.opts.headers['X-Megalodon-Network-Token'],fixture.token);assert.deepEqual(JSON.parse(post.opts.body),{action:'configure',scopes:['192.168.2.0/24'],enabled:true});assert.match(get('network-setup-status').textContent,/Discovery enabled/);
 failure=true;await poll();assert.equal(get('network-panel').classList.contains('snapshot-stale'),true);assert.match(get('network-observed').textContent,/moving traffic is suspended/);failure=false;
 context.state.paused=true;await window.MegalodonNetwork.refresh();assert.equal(get('network-panel').classList.contains('motion-paused'),true);const pausedReads=requests.length;assert.equal([...timers.values()].filter(x=>x.ms===5000).length,0,'paused view does not reschedule network timer');assert.equal(requests.length,pausedReads);context.state.paused=false;
 document.hidden=true;listeners.visibilitychange();const hiddenReads=requests.length;await window.MegalodonNetwork.refresh();assert.equal([...timers.values()].filter(x=>x.ms===5000).length,0,'hidden view does not reschedule network timer');assert.equal(requests.length,hiddenReads);document.hidden=false;listeners.visibilitychange();await settle();await settle();assert.equal(get('network-panel').classList.contains('motion-paused'),false);
 payload={...fixture,edges:[{...fixture.edges[0],target:'missing'}]};await poll();assert.equal(get('network-panel').classList.contains('snapshot-stale'),true,'invalid edge cannot fabricate endpoint');
 payload={...fixture,nodes:[],edges:[],total:0};await poll();assert.match(get('network-map').children[0].textContent,/No observations match/);assert.equal(get('network-next').disabled,true);
 payload=fixture;let release;held=new Promise(r=>release=r);window.MegalodonNetwork.refresh();await settle();const inflight=requests.length;window.MegalodonNetwork.refresh();assert.equal(requests.length,inflight);release();held=null;await settle();
 console.log('network topology, discovery controls and freshness behavior passed');
}).on('error',error=>{console.error(error);process.exitCode=1;});process.on('unhandledRejection',error=>{console.error(error);process.exitCode=1;});
