const assert=require('node:assert/strict'),vm=require('node:vm');let input='';process.stdin.on('data',x=>input+=x);process.stdin.on('end',async()=>{
 const {code,fixture,defense}=JSON.parse(input),nodes=new Map(),listeners={},timers=new Map(),requests=[];let serial=0,mutation,payload=fixture,response=defense,failure=false,held=null,current=Date.parse(fixture.observed_at);
 function element(tag=''){const n={tag,textContent:'',children:[],attributes:{},dataset:{},style:{},events:{},hidden:false,disabled:false,value:'',setAttribute(k,v){this.attributes[k]=String(v);},append(...x){this.children.push(...x);},replaceChildren(...x){this.children=x;this.textContent='';},addEventListener(k,fn){this.events[k]=fn;},focus(){document.activeElement=this;}};Object.defineProperty(n,'innerHTML',{set(){throw Error('unsafe HTML sink')}});return n;}
 const get=id=>{if(!nodes.has(id)){const n=element();n.id=id;nodes.set(id,n);}return nodes.get(id);};
 const document={hidden:false,activeElement:null,getElementById:get,createElement:element,createElementNS:(_ns,t)=>element(t),addEventListener:(k,fn)=>listeners[k]=fn};class Clock extends Date{static now(){return current;}}
 const context={localHudLaunch:{},document,Date:Clock,TextEncoder,TextDecoder,Uint8Array,AbortController,MutationObserver:class{constructor(fn){mutation=fn;}observe(){}},setTimeout(fn,ms){const id=++serial;timers.set(id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id),fetch:async(path,opts)=>{requests.push({path,opts});if(held)await held;if(failure)throw Error('PRIVATE_ERROR');return {ok:true,headers:{get:()=>null},text:async()=>JSON.stringify(path==='/api/operations'?payload:response)};}};
 const settle=()=>new Promise(r=>setImmediate(r)),click=async id=>{get(id).events.click();await settle();await settle();},poll=async ms=>{const entry=[...timers].find(([,x])=>x.ms===ms);assert.ok(entry,`timer ${ms}`);timers.delete(entry[0]);await entry[1].fn();await settle();},text=n=>n.textContent+' '+n.children.map(text).join(' ');
 vm.runInNewContext(code,context);await settle();assert.equal(requests.length,2);assert.equal(get('ops-peers').textContent,'2');assert.equal(get('ops-endpoint-list').children.length,2);assert.equal(get('ops-analyze').disabled,true);assert.equal(get('ops-plan').disabled,true);assert.equal(get('ops-timeline').children[0].tag,'svg');assert.match(get('ops-timeline').attributes['aria-label'],/five-second/);
 const endpoint=get('ops-endpoint-list').children[1];endpoint.focus();endpoint.events.click();await settle();assert.equal(get('ops-inspector-title').textContent,fixture.endpoints[1].ip);assert.equal(document.activeElement,get('ops-inspector-title'));assert.equal(get('ops-plan').disabled,false);assert.match(text(get('ops-endpoint-detail')),/Received by this IP/);assert.match(text(get('ops-endpoint-detail')),/<img src=x>/);assert.equal(requests.filter(r=>r.opts.method==='POST').length,0,'selecting an IP never acts');
 await click('ops-analyze');assert.deepEqual(JSON.parse(requests.find(r=>r.opts.method==='POST').opts.body),{action:'analyze',ip:fixture.endpoints[1].ip});assert.equal(requests.find(r=>r.opts.method==='POST').opts.headers['X-Megalodon-Defense-Token'],defense.token);
 response={...defense,job:{...defense.job,state:'finished',action:'analyze',result:{ip:fixture.endpoints[1].ip,explanation:'<script>attack()</script> Local metadata is incomplete.',proposal:'contain',basis:'local_model'}}};await poll(5000);assert.match(text(get('ops-analysis')),/<script>attack/);assert.equal(get('ops-apply').hidden,true,'model containment advice never supplies an apply action');let posts=requests.filter(r=>r.opts.method==='POST').length;await poll(2000);assert.equal(requests.filter(r=>r.opts.method==='POST').length,posts,'polling never executes model proposals');
 const plan={id:'d'.repeat(32),ip:fixture.endpoints[1].ip,duration_seconds:300,expires_at:new Date(current+60000).toISOString(),effect:'Drop traffic on this PC.',impact:'Shared services can disconnect.'};response={...defense,job:{...defense.job,state:'finished',action:'plan_containment',result:plan},plans:[plan]};await click('ops-plan');assert.equal(get('ops-apply').hidden,false);assert.equal(get('ops-apply').disabled,false);assert.match(text(get('ops-plan-detail')),/Shared services/);posts=requests.filter(r=>r.opts.method==='POST').length;await click('ops-apply');assert.equal(requests.filter(r=>r.opts.method==='POST').length,posts+1);assert.deepEqual(JSON.parse(requests.filter(r=>r.opts.method==='POST').at(-1).opts.body),{action:'apply_containment',plan_id:plan.id});
 response={...defense,active:[{ip:fixture.endpoints[1].ip,present:true,remaining_seconds:299,verified:true,expires_at:new Date(current+300000).toISOString(),verified_at:fixture.observed_at,state:'applied'}]};await poll(5000);assert.equal(get('ops-release').hidden,false);await click('ops-release');assert.deepEqual(JSON.parse(requests.filter(r=>r.opts.method==='POST').at(-1).opts.body),{action:'release_containment',ip:fixture.endpoints[1].ip});
 response={...defense,active:[{ip:fixture.endpoints[1].ip,present:null,remaining_seconds:null,verified:false,expires_at:new Date(current+300000).toISOString(),verified_at:null,state:'needs_review'}]};await poll(5000);assert.match(get('ops-block-status').textContent,/Outcome needs review/);assert.doesNotMatch(get('ops-block-status').textContent,/was verified/);assert.equal(get('ops-release').hidden,false);assert.equal(get('ops-release').textContent,'Release / verify absence');
 response={...response,active:[{...response.active[0],state:'applied',verified:false}]};await poll(5000);assert.match(get('ops-block-status').textContent,/Outcome needs review/,'contradictory applied state never establishes verification');assert.doesNotMatch(get('ops-block-status').textContent,/was verified/);
 // A retained block can still be released after its endpoint leaves packet memory.
 payload={...fixture,endpoints:[]};await poll(2000);assert.equal(get('ops-analyze').disabled,true);assert.equal(get('ops-active-blocks').children.length,1);assert.equal(get('ops-active-blocks').children[0].children[1].disabled,false);
 // Hidden workspace cancels both clocks. Concurrent refreshes do not overlap.
 get('workspace-live').hidden=true;mutation();assert.equal([...timers.values()].filter(x=>[2000,5000,1500].includes(x.ms)).length,0);const hiddenReads=requests.length;await click('ops-refresh');assert.equal(requests.length,hiddenReads);get('workspace-live').hidden=false;mutation();await settle();let release;held=new Promise(r=>release=r);get('ops-refresh').events.click();await settle();const inFlight=requests.length;get('ops-refresh').events.click();assert.equal(requests.length,inFlight);release();held=null;await settle();
 failure=true;await poll(2000);assert.match(get('ops-status').textContent,/unavailable/);assert.equal(get('ops-peers').textContent,'—');assert.equal(get('ops-analyze').disabled,true);failure=false;payload={...fixture,timeline:[],endpoints:[],protocols:[]};await poll(2000);assert.match(text(get('ops-timeline')),/No packet observations/);assert.match(text(get('ops-protocols')),/No transport observations/);response={...defense,job:{...defense.job,state:'finished',action:'analyze',message:'Previous Qwen explanation ready.',result:{ip:fixture.endpoints[1].ip,explanation:'Previous explanation.',proposal:'observe'}}};await poll(5000);assert.match(get('ops-defense-status').textContent,/Select an observed address/);assert.doesNotMatch(get('ops-defense-status').textContent,/explanation ready/);
 // Malformed records cannot become selectable actions.
 payload={...fixture,endpoints:Array(65).fill(fixture.endpoints[0])};await poll(2000);assert.equal(get('ops-analyze').disabled,true);assert.match(get('ops-status').textContent,/unavailable/);
 payload=fixture;await poll(2000);get('ops-endpoint-list').children[0].events.click();assert.equal(get('ops-plan').disabled,true,'local addresses are never offered containment');
 if(process.env.OPERATIONS_FIXTURE_OUTPUT){process.stdout.write(JSON.stringify(Object.fromEntries([...nodes].map(([id,n])=>[id,{text:n.textContent,children:n.children,hidden:n.hidden,disabled:n.disabled,attributes:n.attributes,style:n.style}]))));}else console.log('operations and defensive review behavior passed');
}).on('error',e=>{console.error(e);process.exitCode=1;});process.on('unhandledRejection',e=>{console.error(e);process.exitCode=1;});
