const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {code}=JSON.parse(fs.readFileSync(0,'utf8'));
(async()=>{
 class E{constructor(tag='div'){this.tagName=tag;this.textContent='';this.children=[];this.hidden=false;this.disabled=false;this.value='';this.events={};this.attrs={};this.checked=false;this.open=false;}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}addEventListener(k,fn){this.events[k]=fn;}remove(){}click(){downloads.push(this.download);}focus(){}}
 const nodes=new Map(),get=id=>{if(!nodes.has(id))nodes.set(id,new E());return nodes.get(id);},timers=new Map(),listeners={},calls=[],downloads=[],blobs=[];let t=0,fail=false,loadingRelease=null,printed=0;
 get('reports-range').value='day';get('reports-time').value='09:00';get('reports-frequency').value='daily';get('reports-weekday').value='0';get('reports-schedule-enabled').checked=true;
 get('reports-document').contentWindow={focus(){},print(){printed++;}};
 const rid='a'.repeat(32),newid='b'.repeat(32),saved={id:rid,state:'incomplete',created_at:'2026-09-30T09:00:00Z',start:'2026-09-29T09:00:00Z',end:'2026-09-30T09:00:00Z',title:'Network report',coverage:{partial:true,gaps:['Sensor coverage unknown']},summary:{finding_count:51}};
 let payload={schema:'megalodon-reports-v1',available:true,operator_token:'x'.repeat(32),reports:[saved],job:{state:'idle',processed_records:0},schedule:{enabled:true,time:'09:00',frequency:'daily',weekday:0,timezone:'America/Chicago',next_at:'2026-10-01T14:00:00Z'},local_only:true};
 const html='<!doctype html><html><head><style>body{color:black}</style></head><body><h1>Network report</h1><table><caption>Traffic</caption></table></body></html>';
 const document={hidden:false,getElementById:get,createElement:tag=>new E(tag),body:new E(),addEventListener:(event,fn)=>listeners[event]=fn};
 const context={window:{addEventListener(){}},document,Date,Intl,Number,Map,Set,Math,JSON,TextEncoder,TextDecoder,AbortController,Blob,URL:{createObjectURL:b=>{blobs.push(b);return 'blob:local';},revokeObjectURL(){}},setTimeout:(fn,ms)=>{timers.set(++t,{fn,ms});return t;},clearTimeout:id=>timers.delete(id),fetch:async(path,options)=>{calls.push({path,options});if(fail)throw Error('PRIVATE');let result=payload;if(path.endsWith('/html'))return{ok:true,headers:{get:()=>null},text:async()=>loadingRelease?await new Promise(resolve=>loadingRelease=resolve):html};if(path.includes('/findings?'))result={records:[{id:'seg:1',observed_at:saved.start,source:'<script>bad()</script>',title:'<img onerror=bad()>',severity:'HIGH',src_ip:'192.0.2.1',dst_ip:null,evidence_reference:'segment:event:1'}],total:51,offset:path.includes('offset=50')?50:0};else if(path.endsWith('/create')){payload={...payload,job:{id:'job1',state:'running',progress:20,processed_records:120}};result=payload;}else if(path.endsWith('/cancel')){payload={...payload,job:{state:'cancelled'}};result=payload;}else if(path.endsWith('/schedule')){payload={...payload,schedule:{...payload.schedule,...JSON.parse(options.body)}};result=payload;}else if(path.endsWith('/json'))result={report:'download'};return{ok:true,headers:{get:()=>null},text:async()=>JSON.stringify(result)};}};
 const settle=async()=>{await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));},click=async id=>{get(id).events.click();await settle();},poll=async()=>{const item=[...timers].find(([,v])=>[2000,30000].includes(v.ms));assert.ok(item);timers.delete(item[0]);await item[1].fn();await settle();};
 vm.runInNewContext(code,context);await settle();assert.equal(calls.filter(c=>c.path.endsWith('/html')).length,1);assert.equal(calls.filter(c=>c.options.method==='POST').length,0,'opening reports never generates them');assert.equal(get('reports-document').hidden,false);assert.match(get('reports-document').srcdoc,/\/assets\/report.css/);assert.doesNotMatch(get('reports-document').srcdoc,/<style/);assert.equal(get('reports-print').disabled,true);get('reports-document').events.load();assert.equal(get('reports-print').disabled,false);assert.match(get('reports-coverage').textContent,/Partial coverage/);
 await poll();assert.equal(calls.filter(c=>c.path.endsWith('/html')).length,1,'refresh reuses immutable HTML');await click('reports-save');assert.equal(downloads[0],'megalodon-report-'+rid+'.html');assert.equal(await blobs[0].text(),html,'download retains embedded CSS');await click('reports-print');assert.equal(printed,1);
 get('reports-findings-panel').open=true;get('reports-findings-panel').events.toggle();await settle();assert.equal(get('reports-findings-next').disabled,false);await click('reports-findings-next');assert.ok(calls.some(c=>c.path.includes('offset=50')));const cell=get('reports-findings-rows').children[0].children[1];assert.equal(cell.children[0].textContent,'HIGH · <img onerror=bad()>','untrusted text remains text');
 get('reports-range').value='custom';get('reports-range').events.change();assert.equal(get('reports-custom').hidden,false);get('reports-start').value='invalid';await click('reports-create');assert.match(get('reports-status').textContent,/Choose a start/);assert.equal(calls.filter(c=>c.options.method==='POST').length,0);get('reports-range').value='day';await click('reports-create');const create=calls.find(c=>c.path.endsWith('/create'));assert.equal(create.options.headers['X-Megalodon-Reports-Token'],payload.operator_token);const range=JSON.parse(create.options.body);assert.equal(Date.parse(range.end)-Date.parse(range.start),86400000);assert.equal(get('reports-progress-panel').hidden,false);assert.equal(get('reports-create').disabled,true);await click('reports-cancel');assert.match(get('reports-status').textContent,/cancelled/);
 payload={...payload,job:{state:'ready',report_id:newid},reports:[{...saved,id:newid,state:'ready'},saved]};await poll();assert.equal(get('reports-saved').value,newid,'completed report becomes selected');loadingRelease=true;get('reports-saved').value=rid;get('reports-saved').events.change();await settle();assert.equal(get('reports-document').hidden,true,'previous document is hidden while another report loads');assert.match(get('reports-status').textContent,/Opening saved report/);assert.equal(get('reports-print').disabled,true);const finish=loadingRelease;loadingRelease=null;finish(html);await settle();assert.equal(get('reports-document').hidden,false);await poll();assert.equal(get('reports-saved').value,rid,'manual selection survives refresh');
 get('reports-frequency').value='weekly';get('reports-frequency').events.change();get('reports-time').value='10:30';get('reports-time').events.change();await poll();assert.equal(get('reports-time').value,'10:30','refresh preserves edited schedule');assert.equal(get('reports-weekday-label').hidden,false);get('reports-schedule-form').events.submit({preventDefault(){}});await settle();assert.equal(JSON.parse(calls.find(c=>c.path.endsWith('/schedule')).options.body).time,'10:30');
 fail=true;await poll();assert.equal(get('reports-create').disabled,true);assert.equal(get('reports-save').disabled,false,'cached report survives failed status poll');assert.doesNotMatch(get('reports-status').textContent,/PRIVATE/);document.hidden=true;listeners.visibilitychange();assert.equal([...timers.values()].filter(t=>[2000,30000].includes(t.ms)).length,0);
 console.log('reports read-only load, cached export, print, exact range, cancellation, schedule, paging and failure states passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
