const assert=require('node:assert/strict'),vm=require('node:vm');let input='';process.stdin.on('data',c=>input+=c);process.stdin.on('end',async()=>{
 const {code,fixture}=JSON.parse(input),nodes=new Map(),requests=[],listeners={},timers=new Map();let serial=0,payload=structuredClone(fixture),failure=false,now=Date.parse('2026-10-01T00:00:00Z'),downloads=[],blobs=[],largePages=false;
 function element(tag=''){const n={tag,textContent:'',children:[],attributes:{},dataset:{},style:{},events:{},value:'',hidden:false,disabled:false,parentElement:null,setAttribute(k,v){this.attributes[k]=String(v);},append(...x){this.children.push(...x);for(const c of x)c.parentElement=this;},replaceChildren(...x){this.children=[];this.append(...x);this.textContent='';},addEventListener(k,f){this.events[k]=f;},focus(){document.activeElement=this;},click(){if(tag==='a')downloads.push(this);else this.events.click?.();},remove(){}};Object.defineProperty(n,'innerHTML',{set(){throw Error('Unsafe HTML sink');}});return n;}
 const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};const document={hidden:false,activeElement:null,body:element('body'),getElementById:get,createElement:element,addEventListener:(k,f)=>listeners[k]=f};class Clock extends Date{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}}
 get('workspace-analysis').hidden=true;get('workspace-setup').hidden=true;
 let page={schema:'megalodon-history-v1',records:[{id:'seg-a:1',category:'findings',observed_at:'2026-09-30T23:00:00Z',recorded_at:'2026-09-30T23:00:00Z',source:'<img src=x>',data:{signature:'<script>unsafe()</script>'}}],total:51,offset:0,limit:50,truncated:true,next_cursor:'page2',gaps:['Collection interrupted']};
 const context={localHudLaunch:{},document,Date:Clock,TextEncoder,TextDecoder,Uint8Array,AbortController,Blob,URL:{createObjectURL:blob=>{blobs.push(blob);return 'blob:local';},revokeObjectURL:()=>{}},setTimeout(f,ms){const id=++serial;timers.set(id,{f,ms});return id;},clearTimeout:id=>timers.delete(id),fetch:async(path,options)=>{requests.push({path,options});if(failure)throw Error('PRIVATE');let result=payload;if(path.startsWith('/api/storage/history')){if(largePages){const match=/[?&]cursor=cursor-(\d+)/.exec(path),start=match?Number(match[1]):0,end=Math.min(1200,start+20);result={schema:'megalodon-history-v1',records:Array.from({length:end-start},(_,i)=>({id:'large:'+String(start+i),category:'findings',observed_at:'2026-09-30T23:00:00Z',recorded_at:null,source:'sensor',data:{payload:'x'.repeat(30000)}})),total:1200,offset:start,limit:50,truncated:end<1200,next_cursor:end<1200?'cursor-'+end:null,gaps:[]};}else result=page;}else if(options.method==='POST'){const body=JSON.parse(options.body);if(body.action==='preview')result={schema:'megalodon-storage-preview-v1',preview_id:'preview-1',expires_at:'2026-10-01T00:05:00Z',policy:{...body.policy,recording_mode:body.policy.profile==='server'?'connection_summaries':'packet_metadata'},eligible_bytes:1073741824,eligible_records:12,warnings:[{level:'warning',message:'Saved cases expire too.'}]};else if(body.action==='save_case')result={schema:'megalodon-case-v1',saved:body.ids.length};else result={...payload,enabled:true};}return {ok:true,headers:{get:()=>null},text:async()=>JSON.stringify(result)};}};
 const settle=()=>new Promise(r=>setImmediate(r)),click=async id=>{get(id).events.click();await settle();await settle();},submit=async()=>{get('storage-policy-form').events.submit({preventDefault(){}});await settle();await settle();},poll=async()=>{const e=[...timers].find(([,x])=>x.ms===10000);assert.ok(e,'refresh scheduled');timers.delete(e[0]);await e[1].f();await settle();},text=n=>n.textContent+' '+n.children.map(text).join(' ');
 vm.runInNewContext(code,context);await settle();assert.equal(requests.length,1);assert.equal(get('storage-days').value,'14');assert.equal(get('storage-cap').value,'20');assert.equal(get('storage-preview').disabled,false);assert.match(get('storage-policy-state').textContent,/awaiting activation/);assert.equal(get('ops-storage-coverage').textContent,'2 days retained');assert.equal(get('storage-apply').disabled,true);assert.match(get('storage-estimate-state').textContent,/Provisional/);assert.equal(requests.filter(r=>r.options.method==='POST').length,0,'loading never enables cleanup');
 get('storage-days').value='6';await submit();assert.match(get('storage-feedback').textContent,/7–30/);assert.equal(requests.filter(r=>r.options.method==='POST').length,0);get('storage-days').value='31';await submit();assert.equal(requests.filter(r=>r.options.method==='POST').length,0);get('storage-days').value='14';get('storage-cap').value='4097';await submit();assert.equal(requests.filter(r=>r.options.method==='POST').length,0);
 get('storage-profile').value='server';get('storage-profile').events.change();assert.equal(get('storage-days').value,'7');assert.equal(get('storage-cap').value,'500');assert.match(get('storage-recording-mode').textContent,/reduces packet detail/);await submit();assert.equal(get('storage-preview-panel').hidden,false);assert.match(get('storage-preview-impact').textContent,/12 records/);assert.match(text(get('storage-preview-warnings')),/Saved cases/);assert.equal(get('storage-apply').disabled,false);const preview=requests.find(r=>r.options.method==='POST');assert.equal(preview.options.headers['X-Megalodon-Storage-Token'],fixture.token);assert.deepEqual(JSON.parse(preview.options.body),{action:'preview',policy:{profile:'server',retention_days:7,cap_bytes:500*1073741824}});
 get('storage-cap').value='499';get('storage-cap').events.input();assert.equal(get('storage-apply').disabled,true,'changing settings invalidates the exact preview');assert.equal(get('storage-preview-panel').hidden,true);await submit();await click('storage-apply');assert.deepEqual(JSON.parse(requests.filter(r=>r.options.method==='POST').at(-1).options.body),{action:'apply',preview_id:'preview-1'});assert.match(get('storage-feedback').textContent,/Policy applied/);
 // Retention and space warnings are visible on the HUD as well as Evidence.
 payload={...fixture,estimated_days:3,warnings:[{level:'critical',message:'Less than seven days fit.'}],categories:[{...fixture.categories[0],label:'<script>unsafe()</script>'}],compaction:{state:'ready',building_sources:0,retained_summary_segments:2,raw_oldest_at:'2026-09-30T00:00:00Z',raw_newest_at:'2026-10-01T00:00:00Z',summary_oldest_at:'2026-09-28T00:00:00Z',summary_newest_at:'2026-10-01T00:00:00Z',reclaimed_detail_bytes:1073741824}};await poll();assert.equal(get('ops-storage-coverage').textContent,'2 days retained');assert.equal(get('ops-storage-alert').textContent,'Gross growth exceeds the cap before compact savings. Provisional.');assert.match(get('storage-compact-status').textContent,/2 retained segment/);assert.match(get('storage-summary-range').textContent,/2026/);assert.equal(get('storage-compact-reclaimed').textContent,'1 GiB');assert.match(text(get('storage-evidence-warnings')),/Less than seven/);assert.match(text(get('storage-categories')),/<script>unsafe/);
 // Evidence paging uses a stable cursor instead of shifting offsets.
 get('workspace-analysis').hidden=false;listeners.visibilitychange();await settle();await settle();assert.match(text(get('storage-history-rows')),/<script>unsafe/);assert.match(get('storage-history-gaps').textContent,/Collection interrupted/);assert.equal(get('storage-history-next').disabled,false);page={...page,offset:50,total:51,records:[{...page.records[0],id:'seg-b:2'}],next_cursor:null};await click('storage-history-next');assert.ok(requests.some(r=>r.path.includes('cursor=page2')));assert.equal(get('storage-history-next').disabled,true);assert.equal(get('storage-history-previous').disabled,false);await click('storage-history-previous');assert.ok(requests.at(-1).path.includes('offset=0'));
 page={...page,total:1,offset:0};await click('storage-save-case');assert.deepEqual(JSON.parse(requests.filter(r=>r.options.method==='POST').at(-1).options.body),{action:'save_case',ids:['seg-b:2']});assert.match(get('storage-case-status').textContent,/automatic age and space limits/);page.gaps=Array.from({length:100},(_,i)=>i<50?'repeated coverage gap':String(i)+'x'.repeat(2000));await click('storage-export');assert.equal(downloads.length,1);const exported=JSON.parse(await blobs[0].text());assert.equal(exported.coverage.gaps.filter(g=>g==='repeated coverage gap').length,1,'export deduplicates repeated coverage notes');assert.equal(exported.coverage.gaps_truncated,true);assert.ok(new TextEncoder().encode(JSON.stringify(exported.coverage.gaps)).length<65536,'coverage notes have their own bounded budget');assert.ok(blobs[0].size<=32*1024*1024,'whole file includes manifest within cap');assert.match(get('storage-export-status').textContent,/1 records exported/);assert.match(downloads[0].download,/megalodon-evidence/);await click('storage-export-oldest');assert.ok(requests.at(-1).path.includes('order=oldest'));assert.match(downloads[1].download,/oldest/);
 // A full 32 MiB boundary retains its exact within-page cursor; Continue reaches the rest.
 largePages=true;const beforeLarge=blobs.length;await click('storage-export');assert.equal(get('storage-export-continue').hidden,false);const first=JSON.parse(await blobs[beforeLarge].text());assert.equal(first.coverage.partial,true);assert.ok(blobs[beforeLarge].size<=32*1024*1024);assert.ok(first.coverage.next_page_skip>0,'exercise a boundary within one page');await click('storage-export-continue');const second=JSON.parse(await blobs[beforeLarge+1].text());assert.equal(second.coverage.partial,false);assert.equal(get('storage-export-continue').hidden,true);assert.equal(first.records.length+second.records.length,1200);assert.equal(new Set([...first.records,...second.records].map(r=>r.id)).size,1200,'continuation skips neither nor duplicates records');largePages=false;
 // Expired previews never become an apply request.
 await submit();now+=600000;const posts=requests.filter(r=>r.options.method==='POST').length;await click('storage-apply');assert.equal(requests.filter(r=>r.options.method==='POST').length,posts);failure=true;await poll();assert.equal(get('storage-preview').disabled,true);assert.equal(get('ops-storage-coverage').textContent,'Storage unavailable');
 document.hidden=true;listeners.visibilitychange();assert.equal([...timers.values()].filter(t=>t.ms===10000).length,0);console.log('storage preview, limits, history cursors, export and unavailable behavior passed');
}).on('error',e=>{console.error(e);process.exitCode=1;});process.on('unhandledRejection',e=>{console.error(e);process.exitCode=1;});
