const assert=require('node:assert/strict'),vm=require('node:vm');let input='';process.stdin.on('data',value=>input+=value);
process.stdin.on('end',async()=>{
 const {code,fixture,export_html}=JSON.parse(input),nodes=new Map(),timers=new Map(),requests=[],listeners={};let seq=0,intersection,mutation,payload=fixture,fail=false,large=false,now=Date.parse(fixture.observed_at);
 class Element{constructor(tag='div'){this.tag=tag;this.textContent='';this.children=[];this.value='';this.dataset={};this.attrs={};this.events={};this.hidden=false;this.open=false;this.disabled=false;}append(...values){this.children.push(...values);}replaceChildren(...values){this.children=values;}setAttribute(key,value){this.attrs[key]=value;}addEventListener(key,fn){(this.events[key]??=[]).push(fn);}get firstElementChild(){return this.children[0];}set innerHTML(_){throw Error('Unsafe HTML assignment');}}
 const get=id=>{if(!nodes.has(id))nodes.set(id,new Element());return nodes.get(id);};
 const text=(tag,value,cls)=>{const item=new Element(tag);item.textContent=String(value);if(cls)item.className=cls;return item;};
 const full=node=>[node.textContent,...node.children.map(full)].join(' ');
 const settle=()=>new Promise(resolve=>setImmediate(resolve));
 const event=async(id,key='click')=>{for(const fn of get(id).events[key]||[])await fn();await settle();};
 const document={hidden:false,getElementById:get,createElement:tag=>new Element(tag),addEventListener:(key,fn)=>listeners[key]=fn};
 const clock=class extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}};
 const context={document,Date:clock,localHudLaunch:{},window:{},Intl,TextEncoder,TextDecoder,Uint8Array,AbortController,byId:get,textNode:text,
  setupState:{readiness:null},workflowToolIds:['core','tshark','zeek','suricata','scapy','nftables','clamav','osquery','qwen','nmap'],appsPresenceFreshnessNote:()=> 'Old startup check.',toolPresenceText:()=> 'Not checked',heartbeatLight:()=>text('i',''),heartbeatDetail:()=>text('span',''),installControl:()=>text('span',''),MegalodonControls:{mount(){}},
  IntersectionObserver:class{constructor(fn){intersection=fn;}observe(){}},MutationObserver:class{constructor(fn){mutation=fn;}observe(){}},
  setTimeout(fn,ms){const id=++seq;timers.set(id,{fn,ms});return id;},clearTimeout(id){timers.delete(id);},fetch:async(path,options)=>{requests.push({path,options});if(fail)throw Error('PRIVATE_BACKEND_DIAGNOSTIC');return {ok:true,headers:{get:()=>large?'65537':null},text:async()=>JSON.stringify(payload)};}};
 get('integrations-status-filter').value='ALL';get('integrations-presence-filter').value='ALL';get('integrations-platform').value='linux';
 vm.createContext(context);vm.runInContext(code,context);await settle();assert.equal(requests.length,0,'offscreen tool list does not poll');
 intersection([{isIntersecting:true}]);await settle();assert.equal(requests.length,1);assert.equal(requests[0].path,'/api/support-workflows');assert.equal(requests[0].options.method,'GET');assert.equal(requests[0].options.headers['X-Megalodon-Check'],'1');assert.equal(get('integrations-cards').children.length,10);
 const rows=()=>get('integrations-cards').children;assert.match(full(rows()[0]),/Data connected/);assert.match(full(rows()[1]),/Collecting/);assert.match(full(rows()[3]),/Configured · stopped/);assert.match(full(rows()[4]),/Standby alternative/);assert.match(full(rows()[0]),/2026-09-30 20:09:30 UTC/);assert.match(full(rows()[0]),/Source records  12 records/);
 // Runtime status remains in the same list when static capability reference arrives.
 vm.runInContext("integrationState.snapshot={selected_platform:'linux',workflows:integrationIds.map((id,index)=>({id,software:workflowToolIds[index],selected_status:'optional',input_contract:'Synthetic input',output_contract:'Synthetic output',next_gate:'Synthetic reference',entry_point:null}))}; renderIntegrationMap();",context);
 assert.match(full(rows()[2]),/Capability reference · Optional/);rows()[2].open=true;for(const fn of rows()[2].events.toggle)fn();await event('workflows-refresh');assert.equal(rows()[2].open,true,'expanded tool survives status refresh');
 const escape=value=>String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
 const serialize=node=>'<'+node.tag+(node.className?' class="'+escape(node.className)+'"':'')+Object.entries(node.dataset).map(([key,value])=>' data-'+key+'="'+escape(value)+'"').join('')+(node.open?' open':'')+'>'+escape(node.textContent)+node.children.map(serialize).join('')+'</'+node.tag+'>';
 // Completed inventories remain saved results even when their status envelope is fresh.
 payload={...fixture,tools:fixture.tools.map(row=>['clamav','osquery','nmap'].includes(row.id)?{...row,state:'connected',updated_at:'2025-01-01T00:00:00Z'}:row)};await event('workflows-refresh');
 for(const index of [6,7,9]){assert.match(full(rows()[index]),/Saved result available/);assert.doesNotMatch(full(rows()[index]),/Data connected/);assert.match(full(rows()[index]),/2025-01-01 00:00:00 UTC/);}
 assert.match(full(rows()[1]),/Capture started 2026-09-30 20:09:30 UTC/);assert.match(full(rows()[6]),/Result saved/);assert.match(full(rows()[7]),/Result completed/);assert.match(full(rows()[9]),/Result completed/);
 get('integrations-status-filter').value='saved_result';await event('integrations-status-filter','change');assert.equal(rows().length,3);await event('integrations-clear');
 const readyHTML=rows().map(serialize).join('');payload=fixture;await event('workflows-refresh');
 get('integrations-query').value='Qwen';await event('integrations-query','input');assert.equal(rows().length,1);assert.match(full(rows()[0]),/Qwen/);get('integrations-query').value='';get('integrations-status-filter').value='standby';await event('integrations-status-filter','change');assert.equal(rows().length,1);assert.match(full(rows()[0]),/Scapy/);await event('integrations-clear');assert.equal(rows().length,10);
 // A failed refresh hides current metrics and never retains a connected badge.
 fail=true;await event('workflows-refresh');assert.match(full(rows()[0]),/Status unavailable/);assert.match(full(rows()[0]),/Last observation/);assert.doesNotMatch(full(rows()[0]),/Source records/);assert.doesNotMatch(get('integrations-status').textContent,/PRIVATE_BACKEND/);const failedHTML=rows().map(serialize).join('');
 get('integrations-status-filter').value='connected';await event('integrations-status-filter','change');assert.match(full(rows()[0]),/No tools match/,'failed refresh cannot match old connected state');
 get('integrations-status-filter').value='unavailable';await event('integrations-status-filter','change');assert.equal(rows().length,10,'unavailable filter matches every retained failed row');await event('integrations-clear');fail=false;
 // Invalid responses cannot replace the last valid snapshot, even partially.
 for(const bad of [{...fixture,tools:[fixture.tools[0],fixture.tools[0]]},{...fixture,tools:[{...fixture.tools[0],state:'running'}]},{...fixture,tools:[{...fixture.tools[0],metrics:[{label:'bad',value:'1',unit:''}]}]},{...fixture,tools:[{...fixture.tools[0],updated_at:'unknown'}]},{...fixture,mode:'desktop'}]){payload=bad;await event('workflows-refresh');assert.equal(rows().length,10);assert.match(full(rows()[0]),/Status unavailable/);}
 payload={...fixture,tools:[{...fixture.tools[0],message:'<img src=x onerror=alert(1)>',metrics:[]}]};await event('workflows-refresh');assert.match(full(rows()[0]),/<img src=x/);assert.equal(rows().length,1,'untrusted message is text only');
 payload={...fixture,tools:[]};await event('workflows-refresh');assert.match(full(rows()[0]),/No tool observations/);const emptyHTML=rows().map(serialize).join('');
 payload=fixture;large=true;await event('workflows-refresh');assert.match(get('integrations-status').textContent,/Status unavailable/);large=false;await event('workflows-refresh');now+=31000;vm.runInContext('renderIntegrationMap()',context);assert.match(full(rows()[0]),/Status unavailable/,'old endpoint timestamps cannot remain connected');get('integrations-status-filter').value='connected';await event('integrations-status-filter','change');assert.match(full(rows()[0]),/No tools match/,'expired views cannot match connected state');get('integrations-status-filter').value='unavailable';await event('integrations-status-filter','change');assert.equal(rows().length,10);await event('integrations-clear');now=Date.parse(fixture.observed_at);
 const pollCount=()=>[...timers.values()].filter(timer=>timer.ms===5000).length;
 get('workspace-interfaces').hidden=true;mutation();await settle();assert.equal(pollCount(),0);const count=requests.length;await event('workflows-refresh');assert.equal(requests.length,count,'hidden workspace cannot request');get('workspace-interfaces').hidden=false;mutation();await settle();assert.equal(requests.length,count+1);assert.equal(pollCount(),1);
 intersection([{isIntersecting:false}]);assert.equal(pollCount(),0);intersection([{isIntersecting:true}]);await settle();document.hidden=true;listeners.visibilitychange();assert.equal(pollCount(),0);assert.ok(requests.every(request=>request.options.method==='GET'),'view never starts a tool');
 if(export_html)process.stdout.write(JSON.stringify({readyHTML,failedHTML,emptyHTML}));else console.log('workflow UI behavior passed');
}).on('error',error=>{console.error(error);process.exitCode=1;});process.on('unhandledRejection',error=>{console.error(error);process.exitCode=1;});
