"""Plain-language security reviews, with configuration confined to Setup."""

KNOWLEDGE_HTML = '''
<section class="storage-panel ki-setup" id="knowledge-setup" aria-labelledby="knowledge-title">
 <header class="storage-head"><div><p class="eyebrow">LOCAL AI / SECURITY LIBRARY</p><h3 id="knowledge-title" tabindex="-1">AI knowledge &amp; patterns</h3></div><span id="ki-library-state">Checking library…</span></header>
 <p>Give your selected local model a source-backed second look at network activity. It can explain and suggest; you approve changes to devices or connections.</p>
 <div class="ki-settings"><label><input id="ki-enabled" type="checkbox" checked> Learn usual activity from saved observations</label><label><input id="ki-automatic" type="checkbox" checked> Automatically explain new review candidates (up to 4 per hour)</label><label><input id="ki-updates" type="checkbox" checked> Check approved public references daily at 8 AM on this PC</label></div>
 <div class="ki-actions"><button id="ki-save" type="button" disabled>Save preferences</button><button id="ki-update" type="button" disabled>Check references now</button><button id="ki-rollback" type="button" disabled>Use previous library</button></div>
 <p id="ki-setup-status" role="status" aria-live="polite">Reading current settings…</p>
 <p id="ki-learning">Learning requires 24 eligible hourly samples for each device, interface and sensor.</p><p id="ki-storage">Public references have a separate 512 MiB limit. Your evidence history keeps its existing limit.</p>
 <details><summary>Sources, freshness and licenses</summary><div id="ki-sources"></div><p>Downloaded documents are reference data. They cannot install scripts, alter detector rules or grant permissions. Port registrations from the existing IANA library describe possible services, not confirmed applications.</p></details>
 <details><summary>Search the local security library</summary><form id="ki-search-form"><label for="ki-search">Technique, networking term or exact CVE</label><div class="ki-actions"><input id="ki-search" maxlength="160" placeholder="For example: prompt injection" required><button type="submit">Search references</button></div></form><div id="ki-search-results" aria-live="polite"></div></details>
</section>
'''

REVIEWS_HTML = '''
<section class="storage-panel ki-reviews" id="pattern-reviews" aria-labelledby="pattern-reviews-title">
 <header class="storage-head"><div><p class="eyebrow">A SECOND LOOK</p><h3 id="pattern-reviews-title" tabindex="-1">Activity to review</h3></div><a href="#knowledge-setup">Pattern settings →</a></header>
 <p id="ki-review-state" role="status" aria-live="polite">Waiting for committed observations.</p><button id="ki-cancel" type="button" hidden>Cancel AI explanation</button>
 <div id="ki-reviews"></div><details><summary>Coverage and learning</summary><p id="ki-coverage"></p><p>Expected activity and Incorrect match feedback stay with the review. They do not disable detectors. A pattern alone cannot identify an attacker or prove AI involvement.</p></details>
</section>
'''

HUD_HTML = '''<div class="ki-strip" id="ki-hud"><span id="ki-hud-status" role="status">Local analysis · checking</span><a href="#pattern-reviews">Review activity →</a></div>'''
INSPECTOR_HTML = '''<section class="ki-device" aria-labelledby="ki-device-title"><h4 id="ki-device-title">What this activity means</h4><div id="ki-device-review">Select a device to see its saved reviews.</div></section>'''

KNOWLEDGE_CSS = '''
.ki-strip{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;padding:12px 16px;border:1px solid #31515c;border-radius:8px;margin-bottom:12px;background:#0c222b}
.ki-settings{display:grid;gap:12px;margin:20px 0}.ki-setup .ki-settings label{display:flex;flex-direction:row;align-items:center;gap:12px;max-width:80ch}.ki-setup .ki-settings input{margin:0;padding:0;width:18px;height:18px;min-height:18px;flex:none}
.ki-actions{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}.ki-actions input{min-width:160px;flex:1}.ki-setup details{border-top:1px solid #31515c;padding:16px 0}.ki-setup summary{cursor:pointer;font-weight:600}
.ki-card{border:1px solid #375661;border-left:3px solid #e6ba70;border-radius:10px;padding:20px;margin:16px 0;background:#0d2530}.ki-card h4{margin:0 0 8px;font-size:18px}.ki-card h5{margin:16px 0 4px;font-size:14px;color:#a3e9e3}.ki-card p{margin:5px 0;max-width:90ch}.ki-card details{margin-top:16px}.ki-card pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;max-height:240px;overflow:auto}.ki-card .ki-meta{font-size:12px;color:#aec5ce}.ki-card a,.ki-source a{overflow-wrap:anywhere}.ki-feedback{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.ki-feedback button[aria-pressed=true]{border-color:#a5eee3;background:#17483f}.ki-source{padding:12px 0;border-bottom:1px solid #31515c}.ki-source p{font-size:13px}.ki-device{border-top:1px solid #31515c;margin-top:18px;padding-top:16px}.ki-device .ki-card{padding:12px}.ki-empty{padding:20px;background:#0a1c24;border:1px dashed #31515c;border-radius:10px}
@media(max-width:640px){.ki-card{padding:14px}.ki-actions>*{flex:1 1 100%}.ki-feedback button{flex:1 1 auto}.ki-strip{padding:10px}.ki-card pre{max-width:100%}}
'''

KNOWLEDGE_JS = r'''
(()=>{
 const el=id=>document.getElementById(id);if(el('knowledge-setup')?.getAttribute?.('aria-labelledby')!=='knowledge-title'||typeof setTimeout!=='function')return;
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
 let knowledge=null,patterns=null,selected=null,pending=false,dirty=false,lastKey='',lastLibrary='',deviceReviews=null;
 const stamp=v=>v?new Date(v).toLocaleString():'Not checked yet';
 const link=(text,url)=>{const a=node('a',text);try{const u=new URL(url);if(u.protocol==='https:'){a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';}}catch(_){}return a;};
 async function request(path,body,token){const options=body?{method:'POST',headers:{'Content-Type':'application/json','X-Megalodon-Intelligence-Token':token},body:JSON.stringify(body)}:{headers:{'X-Megalodon-Check':'1'}};const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(path,{...options,signal:controller.signal,credentials:'same-origin',cache:'no-store'});const raw=await r.text();if(raw.length>2097152)throw Error('The local response exceeded its display limit.');const v=JSON.parse(raw);if(!r.ok)throw Error(v.error||'Local analysis is unavailable.');return v;}finally{clearTimeout(timeout);}}
 function details(review){const d=node('details'),s=node('summary','Details: measurements, sources and alternatives');d.append(s);d.append(node('p',`${review.sensor} · ${review.measurement} · ${stamp(review.start)} to ${stamp(review.end)}`,'ki-meta'),node('p',`Required: ${review.required_measurements}`));const pre=node('pre',JSON.stringify(review.facts,null,2));d.append(pre);const a=review.analysis||{};if(a.alternative)d.append(node('p',`Other explanation: ${a.alternative}`));if(a.missing)d.append(node('p',`Missing information: ${a.missing}`));for(const gap of review.missing_information||[])d.append(node('p',gap));for(const ref of a.references||[]){const p=node('p');p.append(link(`${ref.source} · ${ref.identifier} · ${ref.edition}: ${ref.title}`,ref.url));d.append(p);}d.append(node('p','Evidence: '+(review.evidence_refs||[]).join(', '),'ki-meta'));return d;}
 function card(review,compact=false){const box=node('article',undefined,'ki-card');box.append(node('h4',review.device+' · '+review.label),node('p',`${review.interface} · ${review.measurement}`,'ki-meta'));for(const [title,key] of [['What happened','what_happened'],['Why it matters','why_it_matters'],['What you can do','what_you_can_do']])box.append(node('h5',title),node('p',review[key]));const a=review.analysis||{};if(a.explanation)box.append(node('p',a.explanation),node('p','Local model: '+a.model+' · Advice only','ki-meta'));else if(a.message)box.append(node('p',a.message));if(!compact){const actions=node('div',undefined,'ki-actions');const explain=node('button',a.state==='ready'?'Explanation saved':'Ask local AI');explain.type='button';explain.disabled=a.state==='ready'||pending;explain.addEventListener('click',()=>act('/api/intelligence',{action:'analyze',candidate_id:review.id}));actions.append(explain);const inspect=node('button','Review device & response');inspect.type='button';inspect.addEventListener('click',()=>{if(window.MegalodonOperations&&review.device!=='this PC'&&review.device!=='unknown')window.MegalodonOperations.selectEndpoint(review.device);else location.hash='knowledge-setup';});actions.append(inspect);box.append(actions);}box.append(details(review));if(!compact){const feedback=node('div',undefined,'ki-feedback');feedback.setAttribute('aria-label','Your assessment of this activity');for(const choice of ['Expected activity','Investigate','Incorrect match']){const b=node('button',choice);b.type='button';b.setAttribute('aria-pressed',String(review.feedback===choice));b.addEventListener('click',()=>act('/api/intelligence',{action:'feedback',candidate_id:review.id,choice}));feedback.append(b);}box.append(feedback);}return box;}
 function renderDevice(){const target=el('ki-device-review');if(!target)return;const rows=(deviceReviews||patterns?.reviews||[]).filter(r=>r.device===selected);target.replaceChildren(...(rows.length?[card(rows[0],true)]:[node('p',selected?'No saved pattern review for this address. Use Ask local AI to review committed observations.':'Select a device to see its saved reviews.')]));}
 function render(){if(knowledge){el('ki-library-state').textContent=knowledge.state==='updating'?'Updating references…':`${knowledge.entries.toLocaleString()} local references`;el('ki-update').disabled=pending||knowledge.state==='updating';el('ki-rollback').disabled=pending||!knowledge.rollback_available;el('ki-storage').textContent=`Public reference storage: ${(knowledge.used_bytes/1048576).toFixed(1)} MiB of 512 MiB. Separate from your evidence budget. Last check: ${stamp(knowledge.last_check)}.`;if(lastLibrary!==knowledge.generation){lastLibrary=knowledge.generation;el('ki-sources').replaceChildren(...Object.entries(knowledge.sources).map(([key,source])=>{const box=node('div',undefined,'ki-source');box.append(node('strong',source.name),node('p',`${source.edition} · ${source.coverage} · Retrieved ${stamp(source.retrieved_at)}`),node('p',`${source.attribution} · ${source.license}`));const d=node('details');d.append(node('summary','License & content identity'),node('p',source.license_text),node('p','SHA-256: '+source.sha256));box.append(d);return box;}));}if(knowledge.error)el('ki-setup-status').textContent=knowledge.error;else if(el('ki-setup-status').textContent==='Reading current settings…')el('ki-setup-status').textContent='Ready. These preferences are saved on this PC.';}
 if(patterns){const b=patterns.baseline;const learning=`${b.ready_groups} source/device groups ready for comparison. Learning: ${b.largest_group_hours} of 24 required eligible hours in the furthest-along group. Finding-associated and incomplete hours are excluded.`;el('ki-learning').textContent=learning;el('ki-hud-status').textContent=`Local analysis · ${patterns.job.state==='running'?'explaining activity':patterns.unresolved?patterns.unresolved+' reviews to consider':b.ready_groups?'watching for changes':'learning usual activity'}`;el('ki-review-state').textContent=patterns.error||patterns.job.message;el('ki-cancel').hidden=patterns.job.state!=='running';el('ki-coverage').textContent=learning+' '+patterns.gaps.join(' ')+(patterns.truncated?' Showing the first 64 retained reviews.':'');const key=JSON.stringify([patterns.reviews,patterns.job.state]);if(key!==lastKey&&!el('ki-reviews').contains(document.activeElement)){lastKey=key;el('ki-reviews').replaceChildren(...(patterns.reviews.length?patterns.reviews.map(r=>card(r)):[node('p','No pattern reviews yet. MEGALODON is reading saved observations and learning this network. Missing data is not a clean bill of health.','ki-empty')]));renderDevice();}}
 if(knowledge&&patterns){el('ki-save').disabled=pending;if(!dirty){el('ki-enabled').checked=patterns.enabled;el('ki-automatic').checked=patterns.automatic;el('ki-updates').checked=knowledge.enabled;}}}
 async function refresh(){if(pending||document.hidden)return;try{const values=await Promise.all([request('/api/knowledge'),request('/api/intelligence')]);knowledge=values[0];patterns=values[1];render();}catch(e){el('ki-hud-status').textContent='Local analysis unavailable';el('ki-setup-status').textContent=e.message;}}
 async function act(path,body){if(pending||!patterns||!knowledge)return false;pending=true;render();try{await request(path,body,path==='/api/knowledge'?knowledge.token:patterns.token);el('ki-setup-status').textContent='Saved locally.';lastKey='';return true;}catch(e){el('ki-setup-status').textContent=e.message;el('ki-review-state').textContent=e.message;return false;}finally{pending=false;await refresh();}}
 for(const id of ['ki-enabled','ki-automatic','ki-updates'])el(id).addEventListener('change',()=>{dirty=true;});
 el('ki-save').addEventListener('click',async()=>{if(pending||!knowledge||!patterns)return;const choices={enabled:el('ki-enabled').checked,automatic:el('ki-automatic').checked};const updates=el('ki-updates').checked;if(!await act('/api/intelligence',{action:'configure',...choices}))return;if(!await act('/api/knowledge',{action:'configure',enabled:updates})){el('ki-setup-status').textContent='Pattern preferences saved; reference update preference could not be saved. Please retry.';return;}dirty=false;render();});
 el('ki-update').addEventListener('click',()=>act('/api/knowledge',{action:'update'}));el('ki-rollback').addEventListener('click',()=>act('/api/knowledge',{action:'rollback'}));el('ki-cancel').addEventListener('click',()=>act('/api/intelligence',{action:'cancel'}));
 el('ki-search-form').addEventListener('submit',async e=>{e.preventDefault();try{const value=await request('/api/knowledge/search?q='+encodeURIComponent(el('ki-search').value));el('ki-search-results').replaceChildren(...(value.results.length?value.results.map(r=>{const p=node('article',undefined,'ki-source');p.append(link(`${r.title} · ${r.identifier} (${r.edition})`,r.url),node('p',r.excerpt));return p;}):[node('p','No matching reference in the active library.')]));}catch(error){el('ki-search-results').textContent=error.message;}});
 async function deviceReview(address){try{const value=await request('/api/intelligence?device='+encodeURIComponent(address));if(address===selected){deviceReviews=value.reviews;renderDevice();}}catch(_){if(address===selected)el('ki-device-review').textContent='Saved reviews could not be read. Retry the selected device.';}}
 document.addEventListener('megalodon:endpoint-selected',e=>{if(selected===e.detail)return;selected=e.detail;deviceReviews=null;renderDevice();if(selected)deviceReview(selected);});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});let timer;async function poll(){await refresh();timer=setTimeout(poll,15000);}timer=setTimeout(poll,750);
})();
'''


def compose_intelligence(html):
    html=html.replace('<section class="storage-panel" id="storage-setup"',KNOWLEDGE_HTML+'<section class="storage-panel" id="storage-setup"',1)
    html=html.replace('<section class="support-apps" id="support-apps"',HUD_HTML+'<section class="support-apps" id="support-apps"',1)
    marker='<section class="workspace-view" id="workspace-findings" role="tabpanel" aria-labelledby="workspace-tab-findings" hidden>'
    start=html.index(marker)
    insert=html.index('</p>',start)+4
    html=html[:insert]+REVIEWS_HTML+html[insert:]
    html=html.replace('<section class="ops-defense" aria-labelledby="ops-defense-title">',INSPECTOR_HTML+'<section class="ops-defense" aria-labelledby="ops-defense-title">',1)
    return html
