"""Local-only live geographic connection view and legacy history visibility hooks."""

LIVE_GLOBE_HTML = r'''
<section id="live-globe" class="live-globe" aria-labelledby="live-globe-title">
  <header class="live-globe-head"><div><p class="eyebrow">LIVE CONNECTION ATLAS</p><h3 id="live-globe-title" tabindex="-1">Your PC and the wider network</h3><p>Observed packet directions, placed with approximate IP locations.</p></div><span id="live-globe-status" class="live-globe-badge">Checking local capture</span></header>
  <div class="live-monitor-controls"><button id="live-background-start" type="button" disabled>Enable background monitoring</button><button id="live-background-stop" type="button" disabled>Stop monitoring</button><button id="live-interface-change" type="button">Choose interface</button><span id="live-interface-name">Reading saved interface…</span></div>
  <p id="live-background-status" class="live-globe-note">Checking saved monitoring settings…</p><p id="live-action-status" class="live-action-status" role="status" aria-live="polite" aria-atomic="true"></p><button id="live-action-retry" type="button" hidden>Retry local controls</button>
  <div class="live-globe-layout">
    <div class="live-atlas"><div id="live-globe-stage" class="live-globe-stage"><canvas id="live-land" width="640" height="560" aria-hidden="true"></canvas><canvas id="live-flows" width="640" height="560" role="img" aria-label="Geographic reference; live connections are listed alongside it." tabindex="0" aria-describedby="live-motion-status live-camera-status"></canvas><span class="live-globe-map-credit">Natural Earth land · illustrative connection paths</span></div><div class="live-motion-controls"><label class="live-camera-label">View<select id="live-globe-camera"><option value="follow" selected>Follow activity</option><option value="world">World rotation</option><option value="manual">Manual view</option></select></label><label class="live-camera-label live-camera-zoom">Scale<input id="live-globe-zoom" type="range" min="75" max="105" step="1" value="94" aria-label="Globe scale"></label><button type="button" id="live-globe-pause" aria-pressed="false">Pause motion</button><button type="button" id="live-globe-center">Center on internet exit</button><span id="live-motion-status">Drag to turn · arrow keys to rotate</span></div><p id="live-camera-status" class="live-camera-status" role="status">Follow activity · waiting for recent mapped connections.</p><div class="live-direction-key"><span class="live-outbound">→ Outbound</span><span class="live-inbound">← Inbound</span><span class="live-origin-key">◎ Incoming origin</span><span>Other paths · slate</span><span>● Approximate internet exit</span></div><p id="live-origin-status" class="live-globe-note">Incoming origins appear when recent traffic has a mapped source.</p></div>
    <aside class="live-globe-readout" aria-label="Live connection coverage"><p class="eyebrow">LIVE AND RECENTLY RETAINED</p><dl class="live-globe-totals"><div><dt>Recent in tracked data</dt><dd id="live-active-count">—</dd></div><div><dt>Mapped connections</dt><dd id="live-mapped-count">—</dd></div><div><dt>Unmapped connections</dt><dd id="live-unmapped-count">—</dd></div></dl><p id="live-coverage" class="live-globe-note">Coverage is being checked.</p><h4>Your approximate internet exit</h4><p id="live-anchor">Location not loaded.</p><p id="live-precision" class="live-globe-note">IP location describes a network exit, not an exact PC position.</p><button id="live-geography-refresh" type="button" disabled aria-describedby="live-geography-destinations">Update location data</button><button id="live-geography-disable" type="button" disabled aria-describedby="live-geography-destinations">Disable automatic location updates</button><p id="live-geography-opt-in" class="live-globe-note">Checking location-update setting…</p><p id="live-geography-destinations" class="live-globe-note">Downloads the DB-IP database from download.db-ip.com and checks your public internet address with api64.ipify.org. No captured peer addresses are uploaded.</p><p id="live-geography-status" class="live-globe-note">Checking the local location database…</p><p class="live-globe-note">IP location: <a href="https://db-ip.com" target="_blank" rel="noopener noreferrer">DB-IP City Lite</a></p><time id="live-globe-updated" class="live-globe-note">No live snapshot yet.</time><button id="live-globe-retry" type="button" hidden>Retry live connection check</button></aside>
  </div>
  <details class="live-connection-detail"><summary>Connection details <span id="live-connection-count"></span></summary><p class="live-globe-note">Counts accumulate while a connection remains in this bounded live view. TCP / UDP are transport labels; a port does not establish an application protocol.</p><div class="live-connection-table" role="region" aria-label="Recent observed connections" tabindex="0"><table><thead><tr><th scope="col">Endpoints</th><th scope="col">Transport</th><th scope="col">A → B</th><th scope="col">B → A</th><th scope="col">Last packet</th></tr></thead><tbody id="live-connection-rows"><tr><td colspan="5">Waiting for a live snapshot.</td></tr></tbody></table></div></details>
  <details class="live-location-detail"><summary>Location accuracy, animation and coverage</summary><p>Locations come from the local DB-IP City Lite database. Your internet-exit anchor uses your public internet address; a VPN, carrier gateway or proxy can place it away from this PC. Unknown precision is shown as unknown. Location setup downloads the public database from download.db-ip.com and discovers your public internet address through api64.ipify.org. Enabling location setup allows periodic refresh while background monitoring is on. No captured peer address is sent to either service.</p><p>Paths illustrate recently observed connections, not cables, physical origins or measured packet delays. A path appears only while packet evidence in that direction is recent and capture is running. Moving dots indicate the same recent direction evidence; one dot does not represent one packet. Red expanding rings mark approximate sources of recently observed incoming traffic, not attack verdicts or active network probes. Connections at the same mapped location share a ring. Closed, stale or stopped capture produces no paths or moving traffic. Unmapped and private peers stay in the counts and connection list without invented locations.</p><p>Follow activity frames recent mapped exchanges and visits different regions when they cannot fit in one hemisphere. The far side remains hidden; the camera caption reports visible mapped locations. Dragging, arrow keys or changing scale gives you manual camera control. Choose Follow activity to resume, or World rotation to see every longitude. Reduced motion keeps the camera static.</p><p>Up to 512 connections are tracked in bounded memory and up to 128 are returned. Counts cover this cache; they do not represent every connection on the PC. Older connections may be evicted. Recent means packet evidence within 15 seconds while capture runs; it does not mean an operating-system established socket. Rows can remain for 60 seconds after paths disappear. Background monitoring saves your choice and renews bounded capture sessions while the local HUD runs; brief gaps between sessions may occur. Stopping disables automatic resumption.</p><p id="live-location-source" class="live-globe-note"></p></details>
</section>
'''

LIVE_GLOBE_CSS = r'''
.live-globe { margin:1.6rem 0; padding:1.25rem; background:#081923; color:#e7f1f6; border:1px solid #3b6673; border-top:3px solid #86e9e3; border-radius:8px; min-width:0; }
.live-globe h3 { font-size:clamp(1.5rem,2.3vw,2rem); letter-spacing:-.035em; margin:.3rem 0 .5rem; } .live-globe h4 { font-size:1rem; margin:1.4rem 0 .4rem; }
.live-globe .eyebrow { font-size:.875rem; color:#83ded9; } .live-globe p { color:#c4d6df; line-height:1.6; margin:.45rem 0; }
.live-globe-head { display:flex; justify-content:space-between; align-items:flex-start; gap:1rem; flex-wrap:wrap; } .live-globe-head p { max-width:70ch; }
.live-globe-badge { border:1px solid #67828f; color:#d5e5ed; padding:.4rem .65rem; font-size:.875rem; line-height:1.6; border-radius:3px; } .live-globe-badge[data-state="live"] { color:#a9f0dd; border-color:#548a7c; } .live-globe-badge[data-state="stale"],.live-globe-badge[data-state="unavailable"] { color:#f0cf8d; border-color:#8f794a; }
.live-monitor-controls,.live-motion-controls { display:flex; flex-wrap:wrap; align-items:center; gap:.65rem; margin:1rem 0 .5rem; } .live-monitor-controls > span,.live-motion-controls > span { font-size:.875rem; color:#b7cdd9; }
.live-globe button { font:inherit; min-height:44px; padding:.6rem .8rem; border:1px solid #668591; border-radius:4px; color:#e6f4f7; background:#142f3d; cursor:pointer; } .live-globe #live-background-start { background:#8ae9e2; color:#0a222b; font-weight:700; border-color:#8ae9e2; } .live-globe button:hover { filter:brightness(1.15); } .live-globe button:disabled { opacity:.5; cursor:default; filter:none; }
.live-globe :is(button,a,summary,[tabindex]):focus-visible { outline:3px solid #ecd093; outline-offset:3px; } .live-globe a { color:#a8eaf1; }
.live-globe .live-globe-note { font-size:.875rem; line-height:1.6; color:#b8ceda; } .live-action-status { min-height:0; color:#f0cf8d; }
.live-globe-layout { display:grid; grid-template-columns:minmax(0,1.75fr) minmax(245px,.85fr); align-items:center; gap:1.6rem; margin:1rem 0; }
.live-globe-stage { position:relative; width:100%; aspect-ratio:8 / 7; background:radial-gradient(ellipse at 48% 50%,#113443 0,#091c29 55%,#081923 74%); touch-action:pan-y; }
.live-globe-stage canvas { position:absolute; width:100%; height:100%; inset:0; } .live-globe-stage #live-flows { cursor:grab; } .live-globe-stage #live-flows:active { cursor:grabbing; }
.live-globe-map-credit { position:absolute; bottom:.3rem; left:.6rem; right:.6rem; color:#a5becb; font-size:.875rem; text-align:center; pointer-events:none; }
.live-camera-label{display:flex;gap:.45rem;align-items:center;font-size:.8rem;color:#c9dfe6}.live-camera-label select{background:#102b37;color:#e6f4f7;border:1px solid #668591;border-radius:4px;padding:.45rem .6rem;min-height:40px;font:inherit}.live-camera-zoom input{width:100px;accent-color:#87e8dc;cursor:pointer}.live-globe .live-camera-status{font-size:.8rem;color:#b6d7dd;min-height:1.6em;margin:.55rem 0}.live-direction-key { display:flex; flex-wrap:wrap; gap:.5rem 1rem; margin-top:.8rem; font-size:.875rem; color:#c4d8e4; }.live-outbound { color:#72e7e2; } .live-inbound { color:#c7b0fc; } .live-origin-key { color:#ff8791; }
.live-globe-readout { border-left:1px solid #304f5f; padding-left:1.4rem; min-width:0; } .live-globe-totals { margin:.8rem 0; } .live-globe-totals div { display:flex; justify-content:space-between; align-items:baseline; gap:1rem; border-bottom:1px solid #294653; padding:.65rem 0; } .live-globe-totals dt { font-size:.875rem; color:#c0d2dc; } .live-globe-totals dd { font-size:1.65rem; font-variant-numeric:tabular-nums; margin:0; }
.live-globe-readout time { display:block; margin:.75rem 0; } .live-globe summary,.live-globe-history > summary { min-height:44px; cursor:pointer; padding:.75rem 0; line-height:1.6; font-weight:600; } .live-globe details { border-top:1px solid #2d4c5c; margin-top:.8rem; }
.live-connection-table { width:100%; max-width:100%; overflow:auto; } .live-connection-table table { border-collapse:collapse; width:100%; font-size:.875rem; } .live-connection-table th,.live-connection-table td { border-bottom:1px solid #294653; text-align:left; padding:.7rem .6rem; font-variant-numeric:tabular-nums; } .live-connection-table td:first-child { min-width:17rem; overflow-wrap:anywhere; } .live-connection-table td span { display:block; margin:.15rem 0; color:#bdd1dd; } .live-connection-table td:not(:first-child) { white-space:nowrap; }
.live-globe-history { margin:1rem 0; border-top:1px solid #3b596a; } .live-globe-history > summary { font-size:1rem; color:#c9e0e8; } .live-globe-history .room-globe-entry { margin-top:.5rem; }
@media(max-width:880px) { .live-globe-layout { grid-template-columns:1fr; } .live-globe-readout { padding:1rem 0 0; border-left:0; border-top:1px solid #304f5f; } .live-globe-totals { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:.8rem; } .live-globe-totals div { display:block; } .live-globe-totals dd { margin-top:.4rem; } }
@media(max-width:480px) { .live-globe { padding:.9rem; } .live-monitor-controls button { flex:1 1 12rem; } .live-globe-totals { gap:.5rem; } .live-globe-totals dt { min-height:2.6em; } .live-direction-key { gap:.4rem .8rem; } }
'''

LIVE_GLOBE_JS = r'''
const LiveGlobeMath = (()=>{
  const rad=Math.PI/180, dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],scale=(a,n)=>a.map(v=>v*n),add=(a,b)=>a.map((v,i)=>v+b[i]),norm=a=>{const n=Math.hypot(...a);return n?scale(a,1/n):[0,0,0];};
  const vector=(lat,lon)=>[Math.cos(lat*rad)*Math.cos(lon*rad),Math.cos(lat*rad)*Math.sin(lon*rad),Math.sin(lat*rad)];
  function basis(lat,lon){const p=lat*rad,l=lon*rad;return {east:[-Math.sin(l),Math.cos(l),0],north:[-Math.sin(p)*Math.cos(l),-Math.sin(p)*Math.sin(l),Math.cos(p)],front:vector(lat,lon)};}
  const project=(v,b)=>({x:320+236*dot(v,b.east),y:280-236*dot(v,b.north),depth:dot(v,b.front)});
  function route(a,b,lane=1){const av=vector(a.latitude,a.longitude),bv=vector(b.latitude,b.longitude),raw=cross(av,bv),length=Math.hypot(...raw),cos=Math.max(-1,Math.min(1,dot(av,bv))),angle=Math.atan2(length,cos);
    if(angle<1e-6)return [av];const axis=length>1e-8?scale(raw,1/length):norm(cross(av,Math.abs(av[2])<.9?[0,0,1]:[1,0,0])),side=cross(axis,av),points=[];
    for(let i=0;i<=48;i++){const t=i/48,v=add(scale(av,Math.cos(angle*t)),scale(side,Math.sin(angle*t))),offset=lane*.012*Math.sin(Math.PI*t);points.push(scale(add(scale(v,Math.cos(offset)),scale(axis,Math.sin(offset))),1+.12*Math.sin(Math.PI*t)));}return points;
  }
  const fresh=(payload,now)=>!!payload&&now>=Date.parse(payload.generated_at)-2000&&now-Date.parse(payload.generated_at)<=8000;
  const recent=(direction,now)=>direction.packets>0&&direction.last_seen!==null&&now>=Date.parse(direction.last_seen)-2000&&now-Date.parse(direction.last_seen)<=15000;
  function directions(flow,payload,now){if(!fresh(payload,now)||payload.capture.state!=='running'||!flow.active||flow.state==='closed')return [];return [['a_to_b',1],['b_to_a',-1]].filter(([key])=>recent(flow[key],now));}
  const color=(flow,key)=>flow.a.local!==flow.b.local?((key==='a_to_b'&&flow.a.local)||(key==='b_to_a'&&flow.b.local)?'#72e7e2':'#c7b0fc'):'#a8bed3';
  function incoming(flow,payload,now){
    if(flow.a.local===flow.b.local)return null;
    const source=flow.a.local?flow.b:flow.a,key=flow.a.local?'b_to_a':'a_to_b';
    return source.location&&directions(flow,payload,now).some(([direction])=>direction===key)?source:null;
  }
  const angleDelta=(from,to)=>((to-from+540)%360)-180;
  function framing(points){
    const vectors=points.map(p=>vector(p.latitude,p.longitude)),sum=vectors.reduce((a,b)=>add(a,b),[0,0,0]);
    const center=Math.hypot(...sum)>1e-7?norm(sum):vectors[0]||vector(20,-30),spread=Math.max(0,...vectors.map(v=>Math.acos(Math.max(-1,Math.min(1,dot(v,center))))));
    return {latitude:Math.asin(Math.max(-1,Math.min(1,center[2])))/rad,longitude:Math.atan2(center[1],center[0])/rad,spread,zoom:Math.max(.84,Math.min(1,.99-.12*spread/(Math.PI/2)))};
  }
  function scenes(payload,now){
    if(!fresh(payload,now)||payload.capture.state!=='running')return [];
    const flows=payload.connections.filter(flow=>flow.a.location&&flow.b.location&&directions(flow,payload,now).length),points=new Map(),pairs=new Map(),key=p=>`${p.latitude},${p.longitude}`;
    for(const flow of flows){const a=flow.a.location,b=flow.b.location;points.set(key(a),a);points.set(key(b),b);pairs.set([key(a),key(b)].sort().join('|'),[a,b]);}
    if(!points.size)return [];const all=framing([...points.values()]);if(all.spread<Math.PI*.42)return [{key:'all',...all,points:[...points.values()]}];
    // Opposite endpoints cannot be visible together on a sphere. Tour each end
    // instead of choosing an unstable average near antipodes or the date line.
    const result=new Map();for(const [,pair]of [...pairs].sort(([a],[b])=>a.localeCompare(b))){const frame=framing(pair),sets=frame.spread<Math.PI*.42?[pair]:pair.map(p=>[p]);for(const subset of sets){const focus=framing(subset),region=`${Math.round(focus.latitude/20)}:${Math.round(focus.longitude/25)}`;if(!result.has(region))result.set(region,{key:region,...focus,points:subset});}}
    return [...result.values()];
  }
  return {vector,basis,project,route,fresh,directions,color,dot,incoming,angleDelta,framing,scenes};
})();
(() => {
  const el=id=>document.getElementById(id);if(typeof localHudLaunch==='undefined'||!el('live-globe'))return;
  const history=el('live-globe-history'),workspace=el('workspace-live');
  const operationsHistory=el('operations-history');
  const historyVisible=()=>!!history&&history.open&&(!operationsHistory||operationsHistory.open)&&!document.hidden&&!workspace.hidden;
  // Guard only the local composition. Original stored-history functions and Site assets stay intact.
  if(typeof refreshGlobeHour==='function'){const original=refreshGlobeHour;refreshGlobeHour=function(force=false){if(historyVisible())return original(force);};}
  if(typeof startGlobeHour==='function')startGlobeHour=function(){if(!historyVisible()||globeState.hour.started)return;const hour=globeState.hour;hour.started=true;const tick=async()=>{if(!historyVisible()){hour.started=false;return;}if(!state.paused)await refreshGlobeHour();if(historyVisible()&&hour.started)hour.timer=window.setTimeout(tick,Math.max(2,state.config.refresh_seconds)*1000);};tick();};
  if(typeof refreshGlobeLocations==='function'){const original=refreshGlobeLocations;refreshGlobeLocations=function(model){if(historyVisible())return original(model);};}
  if(typeof startGlobeSpin==='function'){const original=startGlobeSpin;startGlobeSpin=function(view){if(historyVisible())return original(view);};}
  if(typeof renderGlobeView==='function'){const original=renderGlobeView;renderGlobeView=function(){if(historyVisible())return original();};}
  if(typeof drawGlobe==='function'){const original=drawGlobe;drawGlobe=function(view){if(historyVisible())return original(view);};}
  function historySync(){if(historyVisible()){if(typeof initializeGlobe==='function'&&typeof globeState!=='undefined'){startGlobeHour();renderGlobeView();}}else{if(typeof stopGlobeSpin==='function')stopGlobeSpin();if(typeof stopGlobeFocusTimer==='function')stopGlobeFocusTimer();if(typeof globeState!=='undefined'){if(globeState.frame!==null)window.cancelAnimationFrame(globeState.frame);globeState.frame=null;if(globeState.hour.timer!==null)window.clearTimeout(globeState.hour.timer);globeState.hour.timer=null;globeState.hour.started=false;}}}
  function revealHistory(){if(history&&window.location&&/^#(?:activity-globe|traffic-volume|live-globe-history)/.test(window.location.hash)){history.open=true;historySync();}}
  if(history)history.addEventListener('toggle',historySync);if(operationsHistory)operationsHistory.addEventListener('toggle',historySync);if(typeof window.addEventListener==='function')window.addEventListener('hashchange',revealHistory);revealHistory();
  const motion=typeof window.matchMedia==='function'?window.matchMedia('(prefers-reduced-motion: reduce)'):{matches:false};
  const view={payload:null,valid:false,pending:false,poll:null,frame:null,controller:null,paused:false,mode:'follow',zoom:.94,cameraInitialized:false,scenes:[],sceneKey:null,sceneSince:0,latitude:20,longitude:-30,elapsed:0,lastFrame:null,lastLand:0,landDirty:true,lastStatus:0,centered:false,drag:null,paths:new Map(),origins:new Map(),land:null,grid:null,contexts:new Map(),size:{width:640,height:560},quality:1.5,frameCost:0,visible:typeof IntersectionObserver==='undefined'};
  const object=v=>v&&typeof v==='object'&&!Array.isArray(v),text=(v,max=512)=>typeof v==='string'&&v.length<=max&&!/[\x00-\x1f\x7f]/.test(v),count=v=>Number.isSafeInteger(v)&&v>=0,stamp=v=>typeof v==='string'&&v.length<=40&&/Z$/.test(v)&&Number.isFinite(Date.parse(v)),optionalStamp=v=>v===null||stamp(v);
  function location(v){return v===null||(object(v)&&Number.isFinite(v.latitude)&&Math.abs(v.latitude)<=90&&Number.isFinite(v.longitude)&&Math.abs(v.longitude)<=180&&text(v.label)&&text(v.country,100)&&text(v.source,100)&&v.approximate===true&&(v.accuracy_radius_km===null||(Number.isFinite(v.accuracy_radius_km)&&v.accuracy_radius_km>=0)));}
  const endpoint=e=>object(e)&&text(e.ip,64)&&typeof e.local==='boolean'&&(e.port===null||(Number.isInteger(e.port)&&e.port>=0&&e.port<=65535))&&location(e.location);
  const direction=d=>object(d)&&count(d.packets)&&count(d.bytes)&&optionalStamp(d.last_seen);
  function checked(v){if(!object(v)||v.schema!=='megalodon-live-connections-v1'||!(v.recording_mode===undefined||['packet_metadata','connection_summaries'].includes(v.recording_mode))||!stamp(v.generated_at)||!object(v.capture)||!['idle','starting','running','stopped','failed'].includes(v.capture.state)||!text(v.capture.interface,64)||!text(v.capture.message)||!['accepted','received','skipped'].every(k=>count(v.capture[k]))||!optionalStamp(v.capture.started_at)||!optionalStamp(v.capture.finished_at)
    ||!object(v.background)||typeof v.background.enabled!=='boolean'||!['stopped','starting','running','waiting','failed'].includes(v.background.state)||!text(v.background.message)||!count(v.background.session_count)
    ||!object(v.geography)||!['ready','missing','unavailable','updating'].includes(v.geography.status)||v.geography.source!=='DB-IP City Lite'||!text(v.geography.message)||!location(v.geography.anchor)||!optionalStamp(v.geography.anchor_checked_at)||!(v.geography.build_date===null||text(v.geography.build_date,40))||!optionalStamp(v.geography.updated_at)||v.geography.attribution_url!=='https://db-ip.com'
    ||!object(v.totals)||!['active','returned','unmapped','packets','bytes'].every(k=>count(v.totals[k]))||typeof v.totals.truncated!=='boolean'||!(v.totals.evicted===undefined||count(v.totals.evicted))||!object(v.limits)||v.limits.idle_seconds!==15||v.limits.retention_seconds!==60||v.limits.max_connections!==128||!(v.limits.tracked_connections===undefined||v.limits.tracked_connections===512)||!Array.isArray(v.connections)||v.connections.length>128
    ||!v.connections.every(c=>object(c)&&typeof c.id==='string'&&/^[a-f0-9]{1,128}$/.test(c.id)&&['TCP','UDP','ICMP','ICMPV6','OTHER'].includes(c.protocol)&&endpoint(c.a)&&endpoint(c.b)&&direction(c.a_to_b)&&direction(c.b_to_a)&&stamp(c.first_seen)&&stamp(c.last_seen)&&typeof c.active==='boolean'&&['recent','closing','closed'].includes(c.state)))throw Error('Invalid live connection snapshot');return v;}
  const visible=()=>!document.hidden&&!workspace.hidden&&view.visible&&!el('live-globe').hidden;
  const current=()=>view.valid&&LiveGlobeMath.fresh(view.payload,Date.now());
  const utc=v=>v?new Date(v).toISOString().replace('T',' ').replace('.000Z',' UTC'):'Unavailable';
  function status(){const p=view.payload,live=current(),isFlow=p?.recording_mode==='connection_summaries',observed=live&&p.connections.some(flow=>LiveGlobeMath.directions(flow,p,Date.now()).length>0);const counts=live?[p.totals.active,p.connections.filter(c=>c.a.location&&c.b.location).length,p.totals.unmapped]:['—','—','—'];for(const [i,id] of ['live-active-count','live-mapped-count','live-unmapped-count'].entries())el(id).textContent=String(counts[i]);if(p){el('live-connection-count').textContent=`· ${p.connections.length}${live?'':' retained'}`;if(!live){el('live-coverage').textContent='Current connection coverage unavailable. Connection rows and locations below are retained from the last successful snapshot.';el('live-background-status').textContent='Monitoring status unavailable; the last received setting is unverified.';el('live-flows').setAttribute('aria-label','Geographic reference from the last successful connection snapshot. Current traffic unavailable.');}}let label=!view.valid?'Connection check unavailable':!live?'Stale · traffic motion stopped':p.capture.state==='running'?(p.capture.accepted===0?(isFlow?'Sensors running · awaiting flow summaries':'Capture running · awaiting packets'):observed?(isFlow?'Sensor-reported exchange':'Live packet observations'):'Capture running · no recent connections'):p.capture.state==='starting'?'Starting capture':'Reference view · capture '+p.capture.state;
    if(!visible())label='View paused while hidden';if(el('live-globe-status').textContent!==label)el('live-globe-status').textContent=label;el('live-globe-status').dataset.state=!view.valid?'unavailable':!live?'stale':p.capture.state==='running'&&observed?'live':'reference';
    el('live-motion-status').textContent=motion.matches?'Reduced motion · static view':view.paused?'Motion paused · drag to inspect':'Drag to turn · arrow keys to rotate';el('live-globe-pause').textContent=view.paused?'Resume motion':'Pause motion';el('live-globe-pause').setAttribute('aria-pressed',view.paused?'true':'false');el('live-globe-pause').disabled=motion.matches;
    cameraStatus();const origins=activeOrigins();el('live-origin-status').textContent=origins.length?`${origins.length} approximate incoming ${origins.length===1?'origin':'origins'} · red indicates observed traffic, not a threat verdict.`:'No recently observed incoming traffic with a mapped source.';}
  function activeOrigins(){const p=view.payload,now=Date.now();return current()?[...view.origins.values()].filter(origin=>origin.flows.some(flow=>LiveGlobeMath.incoming(flow,p,now))):[];}
  function render(){const p=view.payload;if(!p)return;const mapped=p.connections.filter(c=>c.a.location&&c.b.location).length;el('live-coverage').textContent=`${p.totals.packets} ${p.recording_mode==='connection_summaries'?'sensor-reported packets':'packets'} / ${p.totals.bytes} bytes ${p.recording_mode==='connection_summaries'?'reported by connection-summary updates in this session':'observed in this capture session'}. ${p.totals.returned} connection rows retained for up to 60 seconds.${p.totals.evicted===undefined?'':' Cache evictions: '+p.totals.evicted+'.'}${p.totals.truncated?' Partial coverage: return cap or memory eviction.':''}`;
    el('live-background-status').textContent=`Background monitoring ${p.background.enabled?'enabled':'off'} · ${p.background.message}`;
    const anchor=p.geography.anchor;el('live-anchor').textContent=anchor?anchor.label+(anchor.country?' · '+anchor.country:''):'Internet-exit location unavailable';el('live-precision').textContent=anchor?`Approximate IP location · ${anchor.accuracy_radius_km===null?'accuracy radius unknown':anchor.accuracy_radius_km+' km reported accuracy radius'}. This is a network exit, not an exact PC position.`:'Unknown locations remain unmapped; packet collection can continue.';
    el('live-geography-refresh').textContent=p.geography.status==='missing'?'Set up IP locations':p.geography.status==='unavailable'?'Retry location setup':p.geography.status==='updating'?'Updating locations…':'Update location data';el('live-geography-status').textContent=p.geography.message;el('live-location-source').textContent=`DB-IP City Lite build: ${p.geography.build_date||'unknown'} · Database updated: ${utc(p.geography.updated_at)} · Internet exit checked: ${utc(p.geography.anchor_checked_at)}.`;el('live-flows').setAttribute('aria-label',`${mapped} mapped connections; ${p.totals.unmapped} connections lack locations. Packet directions and details are listed below. IP locations are approximate.`);el('live-globe-updated').textContent='Snapshot '+utc(p.generated_at);el('live-connection-count').textContent='· '+p.connections.length;
    const rows=p.connections.map(c=>{const row=document.createElement('tr');const endpoints=document.createElement('td');for(const [name,e] of [['A',c.a],['B',c.b]]){const line=document.createElement('span');line.textContent=`${name}: ${e.local?'This PC · ':''}${e.ip}${e.port===null?'':':'+e.port} · ${e.location?e.location.label+' (approximate; '+(e.location.accuracy_radius_km===null?'precision unknown':e.location.accuracy_radius_km+' km reported radius')+')':'unmapped'}`;endpoints.append(line);}row.append(endpoints);for(const value of [c.protocol,`${c.a_to_b.packets} packets / ${c.a_to_b.bytes} B`,`${c.b_to_a.packets} packets / ${c.b_to_a.bytes} B`,utc(c.last_seen)]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}return row;});if(!rows.length){const row=document.createElement('tr'),cell=document.createElement('td');cell.setAttribute('colspan','5');cell.textContent='No recent connections returned. The globe remains a geographic reference.';row.append(cell);rows.push(row);}el('live-connection-rows').replaceChildren(...rows);
    if(anchor&&!view.centered&&!view.cameraInitialized&&view.mode==='follow'){view.latitude=Math.max(-75,Math.min(75,anchor.latitude));view.longitude=anchor.longitude;view.centered=true;view.landDirty=true;}
    const old=view.paths;view.paths=new Map();for(const c of p.connections){if(!c.a.location||!c.b.location)continue;const key=[c.a.location.latitude,c.a.location.longitude,c.b.location.latitude,c.b.location.longitude].join(',');const cached=old.get(c.id);view.paths.set(c.id,cached&&cached.key===key?cached:{key,forward:LiveGlobeMath.route(c.a.location,c.b.location,1),reverse:LiveGlobeMath.route(c.a.location,c.b.location,-1)});}
    const previous=view.origins;view.origins=new Map();
    for(const flow of p.connections){
      if(flow.a.local===flow.b.local)continue;const source=flow.a.local?flow.b:flow.a,loc=source.location;if(!loc)continue;
      const key=[loc.latitude,loc.longitude].join(',');let origin=view.origins.get(key);
      if(!origin){const cached=previous.get(key);origin={basis:cached?.basis||LiveGlobeMath.basis(loc.latitude,loc.longitude),seed:cached?.seed??((loc.latitude+90)*.017+(loc.longitude+180)*.013)%1,flows:[]};view.origins.set(key,origin);}origin.flows.push(flow);
    }updateScenes();status();draw(true);}
  function updateScenes(){
    view.scenes=current()?LiveGlobeMath.scenes(view.payload,Date.now()):[];
    if(!view.scenes.some(scene=>scene.key===view.sceneKey)){view.sceneKey=view.scenes[0]?.key||null;view.sceneSince=view.elapsed;}
    if(!view.cameraInitialized&&view.scenes.length&&view.mode==='follow'){const scene=view.scenes[0];view.latitude=scene.latitude;view.longitude=scene.longitude;view.zoom=scene.zoom;view.cameraInitialized=true;}
  }
  function cameraStatus(){
    const b=LiveGlobeMath.basis(view.latitude,view.longitude),locations=new Map();
    if(current())for(const flow of view.payload.connections)if(LiveGlobeMath.directions(flow,view.payload,Date.now()).length)for(const endpoint of [flow.a,flow.b])if(endpoint.location){const p=endpoint.location;locations.set(`${p.latitude},${p.longitude}`,p);}
    const shown=[...locations.values()].filter(p=>LiveGlobeMath.dot(LiveGlobeMath.vector(p.latitude,p.longitude),b.front)>.04).length,total=locations.size,index=view.scenes.findIndex(scene=>scene.key===view.sceneKey);
    const mode=view.mode==='follow'?(view.scenes.length>1?`Activity tour · region ${index+1} of ${view.scenes.length}`:'Follow activity'):view.mode==='world'?'World rotation':'Manual view';
    const label=total?`${mode} · ${shown} of ${total} recent mapped locations in the visible hemisphere.${shown<total?' Other locations are on the far side.':''}`:`${mode} · no recent mapped activity; geographic reference.`;
    if(el('live-camera-status').textContent!==label)el('live-camera-status').textContent=label;
    el('live-globe-camera').value=view.mode;if(view.mode!=='manual')el('live-globe-zoom').value=String(Math.round(view.zoom*100));
  }
  function cameraStep(delta){
    if(view.drag||view.mode==='manual')return;
    if(view.mode==='world'){view.longitude=(view.longitude+delta*.0025+540)%360-180;view.latitude+=(20-view.latitude)*(1-Math.exp(-delta/2600));view.zoom+=(.9-view.zoom)*(1-Math.exp(-delta/2600));return;}
    if(!current()||!view.scenes.length)return;
    let index=view.scenes.findIndex(scene=>scene.key===view.sceneKey);if(index<0)index=0;
    if(view.scenes.length>1&&view.elapsed-view.sceneSince>=16000){index=(index+1)%view.scenes.length;view.sceneKey=view.scenes[index].key;view.sceneSince=view.elapsed;}
    const target=view.scenes[index],ease=1-Math.exp(-delta/2200);
    view.latitude+=(target.latitude-view.latitude)*ease;view.longitude=(view.longitude+LiveGlobeMath.angleDelta(view.longitude,target.longitude)*ease+540)%360-180;view.zoom+=(target.zoom-view.zoom)*(1-Math.exp(-delta/3200));
  }
  function manual(){view.mode='manual';view.cameraInitialized=true;el('live-globe-camera').value='manual';el('live-globe-zoom').value=String(Math.round(view.zoom*100));cameraStatus();}
  // Logical projection stays 640 x 560; backing pixels follow the visible surface.
  function measure(){const stage=el('live-globe-stage');if(!stage||typeof stage.getBoundingClientRect!=='function')return;const rect=stage.getBoundingClientRect();if(rect.width>0&&rect.height>0){const ratio=Math.min(1,1400/rect.width,1200/rect.height);view.size={width:rect.width*ratio,height:rect.height*ratio};};view.landDirty=true;}
  function canvas(id){const element=el(id);if(typeof element.getContext!=='function')return null;let context=view.contexts.get(id);if(!context){context=element.getContext('2d');if(context)view.contexts.set(id,context);}if(!context)return null;const dpr=Math.min(view.quality,Math.max(1,window.devicePixelRatio||1)),width=Math.round(view.size.width*dpr),height=Math.round(view.size.height*dpr);if(element.width!==width||element.height!==height){element.width=width;element.height=height;}context.setTransform(1,0,0,1,0,0);context.clearRect(0,0,width,height);const scale=Math.min(width/640,height/560)*view.zoom;context.setTransform(scale,0,0,scale,(width-640*scale)/2,(height-560*scale)/2);return context;}
  function gridPoints(){if(view.grid)return view.grid;const lines=[];for(let lat=-60;lat<=60;lat+=30){const points=[];for(let lon=-180;lon<=180;lon+=3)points.push(LiveGlobeMath.vector(lat,lon));lines.push(points);}for(let lon=-180;lon<180;lon+=30){const points=[];for(let lat=-90;lat<=90;lat+=3)points.push(LiveGlobeMath.vector(lat,lon));lines.push(points);}view.grid=lines;return lines;}
  function landPoints(){if(view.land)return view.land;const result=[],mask=typeof globeMask==='function'?globeMask():null;if(mask)for(let lat=-88.5;lat<=88.5;lat+=1.5)for(let lon=-180;lon<180;lon+=1.5){const x=Math.floor((lon+180)*2)%720,y=Math.max(0,Math.min(359,Math.floor((90-lat)*2))),bit=y*720+x;if(mask[bit>>3]&(1<<(bit&7)))result.push(LiveGlobeMath.vector(lat,lon));}view.land=result;return result;}
  function land(b){const ctx=canvas('live-land');if(!ctx)return;ctx.clearRect(0,0,640,560);const glow=ctx.createRadialGradient(278,225,24,320,280,240);glow.addColorStop(0,'#16414f');glow.addColorStop(1,'#071723');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(320,280,236,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#3b6b79';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#467775';ctx.beginPath();for(const point of landPoints()){const p=LiveGlobeMath.project(point,b);if(p.depth>.008)ctx.rect(p.x-1.35,p.y-1.35,2.7,2.7);}ctx.fill();ctx.strokeStyle='rgba(122,182,190,.16)';ctx.lineWidth=.7;for(const points of gridPoints()){ctx.beginPath();let pen=false;for(const v of points){const p=LiveGlobeMath.project(v,b);if(p.depth<0){pen=false;continue;}if(pen)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y);pen=true;}ctx.stroke();}}

  function path(ctx,points,b,color,alpha){ctx.strokeStyle=color;ctx.globalAlpha=alpha;ctx.lineWidth=1.25;ctx.beginPath();let pen=false;for(const v of points){const p=LiveGlobeMath.project(v,b);if(p.depth<0){pen=false;continue;}if(pen)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y);pen=true;}ctx.stroke();ctx.globalAlpha=1;}
  function particle(ctx,points,b,phase,color){if(points.length<2)return;const index=phase*(points.length-1),lo=Math.floor(index),part=index-lo,a=points[lo],z=points[Math.min(lo+1,points.length-1)],v=a.map((n,i)=>n+(z[i]-n)*part),p=LiveGlobeMath.project(v,b);if(p.depth<0)return;ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=8;ctx.beginPath();ctx.arc(p.x,p.y,2.3,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}
  // Rings lie on the globe surface and share its projection, clock and visibility.
  const ringSteps=Array.from({length:33},(_,i)=>[Math.cos(i*Math.PI/16),Math.sin(i*Math.PI/16)]);
  function originPulse(ctx,origin,b){
    const center=LiveGlobeMath.project(origin.basis.front,b);if(center.depth<=0)return;
    const moving=!view.paused&&!motion.matches,phase=moving?(view.elapsed/2400+origin.seed)%1:.3;
    const angle=(4+24*phase)/236,cos=Math.cos(angle),sin=Math.sin(angle),color='#ff6376';
    ctx.strokeStyle=color;ctx.globalAlpha=moving?.8*(1-phase):.55;ctx.lineWidth=1.7;ctx.beginPath();let pen=false;
    for(const [x,y] of ringSteps){const v=origin.basis.front.map((n,i)=>n*cos+(origin.basis.east[i]*x+origin.basis.north[i]*y)*sin),q=LiveGlobeMath.project(v,b);if(q.depth<0){pen=false;continue;}if(pen)ctx.lineTo(q.x,q.y);else ctx.moveTo(q.x,q.y);pen=true;}ctx.stroke();
    ctx.globalAlpha=1;ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=moving?9:0;ctx.beginPath();ctx.arc(center.x,center.y,3.4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
  }
  function draw(force=false,now=0){if(!visible())return;const b=LiveGlobeMath.basis(view.latitude,view.longitude);land(b);view.lastLand=now;view.landDirty=false;const ctx=canvas('live-flows');if(!ctx)return;ctx.clearRect(0,0,640,560);const p=view.payload;if(!p)return;for(const flow of p.connections){const paths=view.paths.get(flow.id);if(!paths)continue;const active=current()?LiveGlobeMath.directions(flow,p,Date.now()):[];for(const [key] of active){const forward=key==='a_to_b';path(ctx,forward?paths.forward:paths.reverse,b,LiveGlobeMath.color(flow,key),.65);}
      if(!view.paused&&!motion.matches){const seed=parseInt(flow.id.slice(0,6),16)/16777216,phase=(view.elapsed/4800+seed)%1;for(const [key] of active){const forward=key==='a_to_b';particle(ctx,forward?paths.forward:paths.reverse,b,forward?phase:1-phase,LiveGlobeMath.color(flow,key));}}}
    for(const origin of activeOrigins())originPulse(ctx,origin,b);
    if(p.geography.anchor){const a=p.geography.anchor,q=LiveGlobeMath.project(LiveGlobeMath.vector(a.latitude,a.longitude),b);if(q.depth>=0){ctx.strokeStyle='#88eee5';ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(q.x,q.y,7,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#edfdfb';ctx.beginPath();ctx.arc(q.x,q.y,3,0,Math.PI*2);ctx.fill();}}
  }
  function stopFrames(){if(view.frame!==null)window.cancelAnimationFrame(view.frame);view.frame=null;view.lastFrame=null;}
  function animate(now){view.frame=null;if(!visible()||view.paused||motion.matches)return;const delta=view.lastFrame===null?0:Math.min(80,Math.max(0,now-view.lastFrame));view.lastFrame=now;view.elapsed+=delta;if(now-view.lastStatus>=500)updateScenes();cameraStep(delta);const started=typeof performance!=='undefined'?performance.now():0;draw(false,now);if(started){view.frameCost=view.frameCost*.95+(performance.now()-started)*.05;if(view.frameCost>18&&view.quality>1){view.quality=1;view.landDirty=true;}else if(view.frameCost<8&&view.quality<1.5){view.quality=1.5;view.landDirty=true;}}if(now-view.lastStatus>=500){status();view.lastStatus=now;}view.frame=window.requestAnimationFrame(animate);}
  function startFrames(){if(view.frame===null&&visible()&&!view.paused&&!motion.matches&&typeof window.requestAnimationFrame==='function')view.frame=window.requestAnimationFrame(animate);}
  function cancelPoll(){if(view.poll!==null)window.clearTimeout(view.poll);view.poll=null;}
  function schedule(){cancelPoll();if(visible())view.poll=window.setTimeout(read,2000);}
  async function responseBody(response){if(Number(response.headers.get('content-length'))>262144)throw Error('Live response too large');if(response.body&&response.body.getReader){const reader=response.body.getReader(),parts=[];let size=0;try{while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>262144)throw Error('Live response too large');parts.push(part.value);}}catch(error){await reader.cancel();throw error;}const bytes=new Uint8Array(size);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.byteLength;}return JSON.parse(new TextDecoder().decode(bytes));}const text=await response.text();if(new TextEncoder().encode(text).length>262144)throw Error('Live response too large');return JSON.parse(text);}
  async function read(){if(view.pending||!visible())return;cancelPoll();view.pending=true;const controller=new AbortController();view.controller=controller;const timer=window.setTimeout(()=>controller.abort(),8000);try{const response=await fetch('/api/live-connections',{method:'GET',credentials:'same-origin',cache:'no-store',headers:{'X-Megalodon-Check':'1'},signal:controller.signal});if(!response.ok)throw Error('Live read failed');view.payload=checked(await responseBody(response));view.valid=true;el('live-globe-retry').hidden=true;render();}catch(_){view.valid=false;el('live-globe-retry').hidden=false;if(!view.payload){el('live-coverage').textContent='Connection coverage could not be loaded. Retry the live connection check.';el('live-background-status').textContent='Monitoring status unavailable; this view cannot confirm whether capture is running.';el('live-geography-status').textContent='Location data status unavailable.';}status();draw(true);}finally{window.clearTimeout(timer);view.pending=false;view.controller=null;schedule();startFrames();}}
  function sync(){historySync();cancelPoll();stopFrames();if(visible()){status();draw(true);read();startFrames();}else{if(view.controller)view.controller.abort();status();}}
  el('live-globe-retry').addEventListener('click',read);el('live-globe-pause').addEventListener('click',()=>{view.paused=!view.paused;stopFrames();status();draw(true);startFrames();});el('live-globe-center').addEventListener('click',()=>{const anchor=view.payload?.geography.anchor;if(anchor){manual();view.latitude=Math.max(-55,Math.min(55,anchor.latitude));view.longitude=anchor.longitude;view.landDirty=true;cameraStatus();draw(true);}});
  el('live-globe-camera').addEventListener('change',()=>{const mode=el('live-globe-camera').value;if(!['follow','world','manual'].includes(mode))return;view.mode=mode;view.cameraInitialized=true;view.sceneSince=view.elapsed;updateScenes();if(mode==='follow'&&motion.matches&&view.scenes.length){const target=view.scenes[0];view.latitude=target.latitude;view.longitude=target.longitude;view.zoom=target.zoom;}status();draw(true);startFrames();});
  el('live-globe-zoom').addEventListener('input',()=>{const zoom=Number(el('live-globe-zoom').value);manual();if(Number.isFinite(zoom)){view.zoom=Math.max(.75,Math.min(1.05,zoom/100));el('live-globe-zoom').value=String(Math.round(view.zoom*100));}status();draw(true);});
  measure();if(typeof ResizeObserver!=='undefined')new ResizeObserver(()=>{measure();draw(true);}).observe(el('live-globe-stage'));else if(window.addEventListener)window.addEventListener('resize',()=>{measure();draw(true);});
  const surface=el('live-flows');
  // Wheel scrolling belongs to the page. A tap or pointerdown also leaves the
  // follow camera alone; only an intentional drag takes control. Vertical
  // touch gestures remain native page scrolling through touch-action: pan-y.
  surface.addEventListener('pointerdown',event=>{if(event.isPrimary===false||(event.button!==undefined&&event.button!==0))return;view.drag={x:event.clientX,y:event.clientY,startX:event.clientX,startY:event.clientY,touch:event.pointerType==='touch',active:false};});
  surface.addEventListener('pointermove',event=>{if(!view.drag)return;if(event.buttons===0){view.drag=null;return;}const drag=view.drag,dx=event.clientX-drag.startX,dy=event.clientY-drag.startY;if(!drag.active){if(Math.hypot(dx,dy)<6||(drag.touch&&Math.abs(dy)>=Math.abs(dx)))return;drag.active=true;manual();if(surface.setPointerCapture)surface.setPointerCapture(event.pointerId);}view.longitude=(view.longitude+(drag.x-event.clientX)*.25+540)%360-180;view.latitude=Math.max(-75,Math.min(75,view.latitude+(event.clientY-drag.y)*.2));drag.x=event.clientX;drag.y=event.clientY;view.landDirty=true;draw(true);});for(const name of ['pointerup','pointercancel'])surface.addEventListener(name,()=>{view.drag=null;});surface.addEventListener('keydown',event=>{const keys={ArrowLeft:[0,-8],ArrowRight:[0,8],ArrowUp:[8,0],ArrowDown:[-8,0]};if(!keys[event.key])return;event.preventDefault();manual();view.latitude=Math.max(-75,Math.min(75,view.latitude+keys[event.key][0]));view.longitude=(view.longitude+keys[event.key][1]+540)%360-180;view.landDirty=true;draw(true);});
  document.addEventListener('visibilitychange',sync);if(motion.addEventListener)motion.addEventListener('change',()=>{stopFrames();status();draw(true);startFrames();});if(typeof MutationObserver!=='undefined')new MutationObserver(sync).observe(workspace,{attributes:true,attributeFilter:['hidden']});
  if(typeof IntersectionObserver!=='undefined')new IntersectionObserver(entries=>{const visibleNow=entries.some(entry=>entry.isIntersecting);if(view.visible!==visibleNow){view.visible=visibleNow;sync();}},{root:el('workspace-content'),rootMargin:'80px'}).observe(el('live-globe'));
  if(typeof window.megalodonSupportConfiguration==='object')window.megalodonSupportConfiguration.refresh();
  el('live-interface-change').addEventListener('click',()=>{if(window.megalodonSupportConfiguration)window.megalodonSupportConfiguration.open();});
  sync();
})();
'''


def compose_live_globe(html: str, history_html: str) -> str:
    """Keep the full original history markup under one local disclosure."""
    html = html.replace('  <section class="room-globe-entry"', LIVE_GLOBE_HTML + '\n<details class="live-globe-history" id="live-globe-history"><summary>History · stored activity and time sweep</summary>\n  <section class="room-globe-entry"', 1)
    return html.replace(history_html, history_html + '\n</details>', 1)
